# The supported abilities
enum Abilities {
  adaptability
  aerilate
  aftermath
  airlock
  analytic
  angerpoint
  anticipation
  arenatrap
  aromaveil
  aurabreak
  baddreams
  ballfetch
  battery
  battlearmor
  battlebond
  beastboost
  berserk
  bigpecks
  blaze
  bulletproof
  cheekpouch
  chlorophyll
  clearbody
  cloudnine
  colorchange
  comatose
  competitive
  compoundeyes
  contrary
  corrosion
  cottondown
  cursedbody
  cutecharm
  damp
  dancer
  darkaura
  dauntlessshield
  dazzling
  defeatist
  defiant
  deltastream
  desolateland
  disguise
  download
  drizzle
  drought
  dryskin
  earlybird
  effectspore
  electricsurge
  emergencyexit
  fairyaura
  filter
  flamebody
  flareboost
  flashfire
  flowergift
  flowerveil
  fluffy
  forecast
  forewarn
  friendguard
  frisk
  fullmetalbody
  furcoat
  galewings
  galvanize
  gluttony
  gooey
  gorillatactics
  grasspelt
  grassysurge
  gulpmissile
  guts
  harvest
  healer
  heatproof
  heavymetal
  honeygather
  hugepower
  hungerswitch
  hustle
  hydration
  hypercutter
  icebody
  iceface
  icescales
  illuminate
  illusion
  immunity
  imposter
  infiltrator
  innardsout
  innerfocus
  insomnia
  intimidate
  intrepidsword
  ironbarbs
  ironfist
  justified
  keeneye
  klutz
  leafguard
  levitate
  libero
  lightmetal
  lightningrod
  limber
  liquidooze
  liquidvoice
  longreach
  magicbounce
  magicguard
  magician
  magmaarmor
  magnetpull
  marvelscale
  megalauncher
  merciless
  mimicry
  minus
  mirrorarmor
  mistysurge
  moldbreaker
  moody
  motordrive
  mountaineer
  moxie
  multiscale
  multitype
  mummy
  naturalcure
  neuroforce
  noability
  neutralizinggas
  noguard
  normalize
  oblivious
  overcoat
  overgrow
  owntempo
  parentalbond
  persistent
  pastelveil
  perishbody
  pickpocket
  pickup
  pixilate
  plus
  poisonheal
  poisonpoint
  poisontouch
  powerconstruct
  powerofalchemy
  powerspot
  prankster
  pressure
  primordialsea
  prismarmor
  propellertail
  protean
  psychicsurge
  punkrock
  purepower
  queenlymajesty
  quickfeet
  rkssystem
  raindish
  rattled
  rebound
  receiver
  reckless
  refrigerate
  regenerator
  ripen
  rivalry
  rockhead
  roughskin
  runaway
  sandforce
  sandrush
  sandspit
  sandstream
  sandveil
  sapsipper
  schooling
  scrappy
  screencleaner
  serenegrace
  shadowshield
  shadowtag
  shedskin
  sheerforce
  shellarmor
  shielddust
  shieldsdown
  simple
  skilllink
  slowstart
  slushrush
  sniper
  snowcloak
  snowwarning
  solarpower
  solidrock
  soulheart
  soundproof
  speedboost
  stakeout
  stall
  stalwart
  stamina
  stancechange
  static
  steadfast
  steamengine
  steelworker
  steelyspirit
  stench
  stickyhold
  stormdrain
  strongjaw
  sturdy
  suctioncups
  superluck
  surgesurfer
  swarm
  sweetveil
  swiftswim
  symbiosis
  synchronize
  tangledfeet
  tanglinghair
  technician
  telepathy
  teravolt
  thickfat
  tintedlens
  torrent
  toughclaws
  toxicboost
  trace
  triage
  truant
  turboblaze
  unaware
  unburden
  unnerve
  victorystar
  vitalspirit
  voltabsorb
  wanderingspirit
  waterabsorb
  waterbubble
  watercompaction
  waterveil
  weakarmor
  whitesmoke
  wimpout
  wonderguard
  wonderskin
  zenmode
}

# A Pokémon's abilities entry
type AbilitiesEntry {
  # The first ability of a Pokémon
  first: String!
  # The second ability of a Pokémon
  second: String
  # The hidden ability of a Pokémon
  hidden: String
  # The special ability of a Pokémon
  special: String
}

# A single Pokémon ability entry
type AbilityEntry {
  # The long description for an ability
  desc: String
  # The short description for an ability
  shortDesc: String!
  # The name for an ability
  name: String!
  # Bulbapedia page for an ability
  bulbapediaPage: String!
  # Serebii page for an ability
  serebiiPage: String!
  # Smogon page for an ability
  smogonPage: String!
}

# A Pokémon's details entry
type DexDetails {
  # The dex number for a Pokémon
  num: Int!
  # The species name for a Pokémon
  species: String!
  # The types for a Pokémon
  types: [String!]!
  # The abilities for a Pokémon
  abilities: AbilitiesEntry!
  # Base stats for a Pokémon
  baseStats: StatsEntry!
  # The colour of a Pokémon as listed in the Pokedex
  color: String!
  # The egg groups a Pokémon is in
  eggGroups: [String!]
  # The evolution level, or special method, for a Pokémon
  evolutionLevel: String
  # The raw evos of a Pokémon
  evos: [String!]
  # The raw prevo of a Pokémon
  prevo: String
  # The form identifier of a Pokémon
  forme: String
  # The single letter identifier of the form
  formeLetter: String
  # The gender data for a Pokémon
  gender: GenderEntry!
  # The height of a Pokémon in meters
  height: Float!
  # The weight of a Pokémon in kilograms
  weight: Float!
  # Base form if this entry describes an alternate form
  baseForme: String
  # Base species if this entry describes a special form
  baseSpecies: String
  # Any other forms for a Pokémon
  otherFormes: [String!]
  # The total of all base stats for a Pokémon
  baseStatsTotal: Int!
  # The evolutions for a Pokémon, if any
  evolutions: [DexDetails!]
  # The preevolutions for a Pokémon, if any
  preevolutions: [DexDetails!]
  # The flavortexts for a Pokémon
  flavorTexts: [FlavorEntry!]!
  # The sprite for a Pokémon. For most Pokémon this will be the animated gif, with
  # some exceptions that were older-gen exclusive
  sprite: String!
  # The shiny sprite for a Pokémon. For most Pokémon this will be the animated
  # gif, with some exceptions that were older-gen exclusive
  shinySprite: String!
  # The smogon tier a Pokémon falls under
  smogonTier: String!
  # Bulbapedia page for a Pokémon
  bulbapediaPage: String!
  # Serebii page for a Pokémon
  serebiiPage: String!
  # Smogon page for a Pokémon
  smogonPage: String!
}

# A single Pokedex entry
type DexEntry {
  # The dex number for a Pokémon
  num: Int!
  # The species name for a Pokémon
  species: String!
  # The types for a Pokémon
  types: [String!]!
  # The abilities for a Pokémon
  abilities: AbilitiesEntry!
  # Base stats for a Pokémon
  baseStats: StatsEntry!
  # The colour of a Pokémon as listed in the Pokedex
  color: String!
  # The egg groups a Pokémon is in
  eggGroups: [String!]
  # The evolution level, or special method, for a Pokémon
  evolutionLevel: String
  # The raw evos of a Pokémon
  evos: [String!]
  # The raw prevo of a Pokémon
  prevo: String
  # The form identifier of a Pokémon
  forme: String
  # The single letter identifier of the form
  formeLetter: String
  # The gender data for a Pokémon
  gender: GenderEntry!
  # The height of a Pokémon in meters
  height: Float!
  # The weight of a Pokémon in kilograms
  weight: Float!
  # Base form if this entry describes an alternate form
  baseForme: String
  # Base species if this entry describes a special form
  baseSpecies: String
  # Any other forms for a Pokémon
  otherFormes: [String!]
}

# A flavor text entry for a Pokémon
type FlavorEntry {
  # The name of the game this flavor text is from
  game: String!
  # The flavor text for this entry
  flavor: String!
}

# A Pokémon gender ratio entry
type GenderEntry {
  # The percentage of male occurrences
  male: String!
  # The percentage for female occurrences
  female: String!
}

# A single item entry
type ItemEntry {
  # The long description for an item
  desc: String!
  # The long description for an item
  shortDesc: String
  # The name for an item
  name: String!
  # Whether an item is non-standard, and if it is why
  isNonstandard: String
  # The sprite for an item
  sprite: String!
  # The generation in which this item was introduced
  generationIntroduced: Int!
  # Bulbapedia page for an item
  bulbapediaPage: String!
  # Serebii page for an item
  serebiiPage: String!
  # Smogon page for an item
  smogonPage: String!
}

# The supported items
enum Items {
  abomasite
  absolite
  absorbbulb
  adamantorb
  adrenalineorb
  aerodactylite
  aggronite
  aguavberry
  airballoon
  alakazite
  aloraichiumz
  altarianite
  ampharosite
  apicotberry
  armorfossil
  aspearberry
  assaultvest
  audinite
  babiriberry
  banettite
  beastball
  beedrillite
  belueberry
  berry
  berryjuice
  berrysweet
  berserkgene
  bigroot
  bindingband
  bitterberry
  blackbelt
  blackglasses
  blacksludge
  blastoisinite
  blazikenite
  blueorb
  blukberry
  blunderpolicy
  bottlecap
  brightpowder
  buggem
  bugmemory
  buginiumz
  burndrive
  burntberry
  cameruptite
  cellbattery
  charcoal
  charizarditex
  charizarditey
  chartiberry
  cheriberry
  cherishball
  chestoberry
  chilanberry
  chilldrive
  chippedpot
  choiceband
  choicescarf
  choicespecs
  chopleberry
  clawfossil
  cloversweet
  cobaberry
  colburberry
  cornnberry
  coverfossil
  crucibellite
  crackedpot
  custapberry
  damprock
  darkgem
  darkmemory
  darkiniumz
  dawnstone
  decidiumz
  deepseascale
  deepseatooth
  destinyknot
  diancite
  diveball
  domefossil
  dousedrive
  dracoplate
  dragonfang
  dragongem
  dragonmemory
  dragonscale
  dragoniumz
  dreadplate
  dreamball
  dubiousdisc
  durinberry
  duskball
  duskstone
  earthplate
  eeviumz
  ejectbutton
  ejectpack
  electirizer
  electricgem
  electricmemory
  electricseed
  electriumz
  energypowder
  enigmaberry
  eviolite
  expertbelt
  fairiumz
  fairygem
  fairymemory
  fastball
  fightinggem
  fightingmemory
  fightiniumz
  figyberry
  firegem
  firememory
  firestone
  firiumz
  fistplate
  flameorb
  flameplate
  floatstone
  flowersweet
  flyinggem
  flyingmemory
  flyiniumz
  focusband
  focussash
  fossilizedbird
  fossilizeddino
  fossilizeddrake
  fossilizedfish
  friendball
  fullincense
  galladite
  ganlonberry
  garchompite
  gardevoirite
  gengarite
  ghostgem
  ghostmemory
  ghostiumz
  glalitite
  goldberry
  goldbottlecap
  grassgem
  grassmemory
  grassiumz
  grassyseed
  greatball
  grepaberry
  gripclaw
  griseousorb
  groundgem
  groundmemory
  groundiumz
  gyaradosite
  habanberry
  hardstone
  healball
  heatrock
  heavyball
  heavydutyboots
  helixfossil
  heracronite
  hondewberry
  houndoominite
  iapapaberry
  iceberry
  icegem
  icememory
  icestone
  icicleplate
  iciumz
  icyrock
  inciniumz
  insectplate
  ironball
  ironplate
  jabocaberry
  jawfossil
  kangaskhanite
  kasibberry
  kebiaberry
  keeberry
  kelpsyberry
  kingsrock
  kommoniumz
  laggingtail
  lansatberry
  latiasite
  latiosite
  laxincense
  leafstone
  leek
  leftovers
  leppaberry
  levelball
  liechiberry
  lifeorb
  lightball
  lightclay
  lopunnite
  loveball
  lovesweet
  lucarionite
  luckypunch
  lumberry
  luminousmoss
  lunaliumz
  lureball
  lustrousorb
  luxuryball
  lycaniumz
  machobrace
  magmarizer
  magnet
  magoberry
  magostberry
  mail
  manectite
  marangaberry
  marshadiumz
  masterball
  mawilite
  meadowplate
  medichamite
  mentalherb
  metagrossite
  metalcoat
  metalpowder
  metronome
  mewniumz
  mewtwonitex
  mewtwonitey
  micleberry
  mimikiumz
  mindplate
  mintberry
  miracleberry
  miracleseed
  mistyseed
  moonball
  moonstone
  muscleband
  mysteryberry
  mysticwater
  nanabberry
  nestball
  netball
  nevermeltice
  nomelberry
  normalgem
  normaliumz
  occaberry
  oddincense
  oldamber
  oranberry
  ovalstone
  przcureberry
  psncureberry
  pamtreberry
  parkball
  passhoberry
  payapaberry
  pechaberry
  persimberry
  petayaberry
  pidgeotite
  pikaniumz
  pikashuniumz
  pinapberry
  pinkbow
  pinsirite
  pixieplate
  plumefossil
  poisonbarb
  poisongem
  poisonmemory
  poisoniumz
  pokeball
  polkadotbow
  pomegberry
  poweranklet
  powerband
  powerbelt
  powerbracer
  powerherb
  powerlens
  powerweight
  premierball
  primariumz
  prismscale
  protectivepads
  protector
  psychicgem
  psychicmemory
  psychicseed
  psychiumz
  qualotberry
  quickball
  quickclaw
  quickpowder
  rabutaberry
  rarebone
  rawstberry
  razorclaw
  razorfang
  razzberry
  reapercloth
  redcard
  redorb
  repeatball
  ribbonsweet
  rindoberry
  ringtarget
  rockgem
  rockincense
  rockmemory
  rockiumz
  roseincense
  rockyhelmet
  roomservice
  rootfossil
  roseliberry
  rowapberry
  rustedshield
  rustedsword
  sablenite
  sachet
  safariball
  safetygoggles
  sailfossil
  salacberry
  salamencite
  sceptilite
  scizorite
  scopelens
  seaincense
  sharpbeak
  sharpedonite
  shedshell
  shellbell
  shinystone
  shockdrive
  shucaberry
  silkscarf
  silverpowder
  sitrusberry
  skullfossil
  skyplate
  slowbronite
  smoothrock
  snorliumz
  snowball
  softsand
  solganiumz
  souldew
  spelltag
  spelonberry
  splashplate
  spookyplate
  sportball
  starfberry
  steelgem
  steelmemory
  steeliumz
  starsweet
  steelixite
  stick
  stickybarb
  stoneplate
  strawberrysweet
  sunstone
  swampertite
  sweetapple
  tamatoberry
  tangaberry
  tapuniumz
  tartapple
  terrainextender
  thickclub
  throatspray
  thunderstone
  timerball
  toxicorb
  toxicplate
  twistedspoon
  tyranitarite
  ultraball
  ultranecroziumz
  upgrade
  utilityumbrella
  venusaurite
  wacanberry
  watergem
  watermemory
  waterstone
  wateriumz
  watmelberry
  waveincense
  weaknesspolicy
  wepearberry
  whippeddream
  whiteherb
  widelens
  wikiberry
  wiseglasses
  yacheberry
  zapplate
  zoomlens
}

# The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
scalar JSONObject

# A learnset entry
type LearnsetEntry {
  # The moves that can be learned through levelling up
  levelUpMoves: [LearnsetLevelUpMove!]
  # The moves that can be learned through virtual console transfer
  virtualTransferMoves: [LearnsetMove!]
  # The moves that can be learned from a move tutor
  tutorMoves: [LearnsetMove!]
  # The moves that can be learned from a Technical Machine or Technical Record
  tmMoves: [LearnsetMove!]
  # The moves that can be passed as egg moves
  eggMoves: [LearnsetMove!]
  # The moves that are exclusive to event variants of the Pokémon
  eventMoves: [LearnsetMove!]
  # The moves that are exclusively learned in the Unova Dream World
  dreamworldMoves: [LearnsetMove!]
  # The dex number for a Pokémon
  num: Int!
  # The species name for a Pokémon
  species: String!
  # The sprite for the Pokémon
  sprite: String!
  # The shiny sprite for the Pokémon
  shinySprite: String!
  # The PokéDex colour for the Pokémon
  color: String!
}

# A learnset level up move entry
type LearnsetLevelUpMove {
  # The name of the move
  name: String
  # The generation in which this pokemon learned the move this way
  generation: Int
  # The level at which the move is learned
  level: Int
}

# A learnset move entry
type LearnsetMove {
  # The name of the move
  name: String
  # The generation in which this pokemon learned the move this way
  generation: Int
}

# A single Pokémon move entry
type MoveEntry {
  # The name for a move
  name: String!
  # The short description for a move
  shortDesc: String!
  # The type for a move
  type: String!
  # The base power for a move
  basePower: String!
  # The power points for a move
  pp: Int!
  # The category for a move
  category: String!
  # The accuracy for a move
  accuracy: Int!
  # The priority for a move
  priority: Int!
  # The target for a move
  target: String!
  # The contest type for a move
  contestType: String
  # Bulbapedia page for a move
  bulbapediaPage: String!
  # Serebii page for a move
  serebiiPage: String!
  # Smogon page for a move
  smogonPage: String!
  # Whether a move is non-standard, and if it is why
  isNonstandard: String
  # Whether this move is a Z-Move, and if it is the Z-Crystal required to trigger it
  isZ: String
  # Whether this move is a G-MAX move, and if it is which Gigantamaxed Pokémon can use it
  isGMax: String
  # The long description for a move
  desc: String
}

# The supported moves
enum Moves {
  absorb
  accelerock
  acid
  acidarmor
  aciddownpour
  acidspray
  acrobatics
  acupressure
  aerialace
  aeroblast
  afteryou
  agility
  aircutter
  airslash
  alloutpummeling
  allyswitch
  amnesia
  anchorshot
  ancientpower
  appleacid
  aquajet
  aquaring
  aquatail
  armthrust
  aromatherapy
  aromaticmist
  assist
  assurance
  astonish
  attackorder
  attract
  aurasphere
  aurawheel
  aurorabeam
  auroraveil
  autotomize
  avalanche
  babydolleyes
  baddybad
  banefulbunker
  barrage
  barrier
  batonpass
  beakblast
  beatup
  belch
  behemothbash
  behemothblade
  bellydrum
  bestow
  bide
  bind
  bite
  blackholeeclipse
  blastburn
  blazekick
  blizzard
  block
  bloomdoom
  blueflare
  bodypress
  bodyslam
  boltbeak
  boltstrike
  boneclub
  bonerush
  bonemerang
  boomburst
  bounce
  bouncybubble
  bravebird
  branchpoke
  breakingswipe
  breakneckblitz
  brickbreak
  brine
  brutalswing
  bubble
  bubblebeam
  bugbite
  bugbuzz
  bulkup
  bulldoze
  bulletpunch
  bulletseed
  burnup
  buzzybuzz
  calmmind
  camouflage
  captivate
  catastropika
  celebrate
  charge
  chargebeam
  charm
  chatter
  chipaway
  circlethrow
  clamp
  clangingscales
  clangoroussoul
  clangoroussoulblaze
  clearsmog
  closecombat
  coil
  cometpunch
  confide
  confuseray
  confusion
  constrict
  continentalcrush
  conversion
  conversion2
  copycat
  coreenforcer
  corkscrewcrash
  cosmicpower
  cottonguard
  cottonspore
  counter
  courtchange
  covet
  crabhammer
  craftyshield
  crosschop
  crosspoison
  crunch
  crushclaw
  crushgrip
  curse
  cut
  darkpulse
  darkvoid
  darkestlariat
  dazzlinggleam
  decorate
  defendorder
  defensecurl
  defog
  destinybond
  detect
  devastatingdrake
  diamondstorm
  dig
  disable
  disarmingvoice
  discharge
  dive
  dizzypunch
  doomdesire
  doublehit
  doubleironbash
  doublekick
  doubleslap
  doubleteam
  doubleedge
  dracometeor
  dragonascent
  dragonbreath
  dragonclaw
  dragondance
  dragondarts
  dragonhammer
  dragonpulse
  dragonrage
  dragonrush
  dragontail
  drainpunch
  drainingkiss
  dreameater
  drillpeck
  drillrun
  drumbeating
  dualchop
  dynamicpunch
  dynamaxcannon
  earthpower
  earthquake
  echoedvoice
  eerieimpulse
  eggbomb
  electricterrain
  electrify
  electroball
  electroweb
  embargo
  ember
  encore
  endeavor
  endure
  energyball
  entrainment
  eruption
  eternabeam
  explosion
  extrasensory
  extremeevoboost
  extremespeed
  facade
  fairylock
  fairywind
  fakeout
  faketears
  falsesurrender
  falseswipe
  featherdance
  feint
  feintattack
  fellstinger
  fierydance
  finalgambit
  fireblast
  firefang
  firelash
  firepledge
  firepunch
  firespin
  fishiousrend
  firstimpression
  fissure
  flail
  flameburst
  flamecharge
  flamewheel
  flamethrower
  flareblitz
  flash
  flashcannon
  flatter
  fleurcannon
  fling
  floatyfall
  floralhealing
  flowershield
  fly
  flyingpress
  focusblast
  focusenergy
  focuspunch
  followme
  forcepalm
  foresight
  forestscurse
  foulplay
  freezeshock
  freezedry
  freezyfrost
  frenzyplant
  frostbreath
  frustration
  furyattack
  furycutter
  furyswipes
  fusionbolt
  fusionflare
  futuresight
  gastroacid
  geargrind
  gearup
  genesissupernova
  geomancy
  gigadrain
  gigaimpact
  gigavolthavoc
  glaciate
  glare
  glitzyglow
  gmaxbefuddle
  gmaxcentiferno
  gmaxchistrike
  gmaxcuddle
  gmaxdepletion
  gmaxfinale
  gmaxtartness
  gmaxvolcalith
  gmaxvoltcrash
  gmaxwildfire
  gmaxwindrage
  gmaxfoamburst
  gmaxgoldrush
  gmaxgravitas
  gmaxmalodor
  gmaxmeltdown
  gmaxstonesurge
  gmaxstunshock
  gmaxsweetness
  gmaxterror
  gmaxreplenish
  gmaxresonance
  gmaxsandblast
  gmaxsmite
  gmaxsnooze
  gmaxsteelsurge
  grassknot
  grasspledge
  grasswhistle
  grassyterrain
  gravapple
  gravity
  growl
  growth
  grudge
  guardsplit
  guardswap
  guardianofalola
  guillotine
  gunkshot
  gust
  gyroball
  hail
  hammerarm
  happyhour
  harden
  haze
  headcharge
  headsmash
  headbutt
  healbell
  healblock
  healorder
  healpulse
  healingwish
  heartstamp
  heartswap
  heatcrash
  heatwave
  heavyslam
  helpinghand
  hex
  hiddenpower
  highhorsepower
  highjumpkick
  holdback
  holdhands
  honeclaws
  hornattack
  horndrill
  hornleech
  howl
  hurricane
  hydrocannon
  hydropump
  hydrovortex
  hyperbeam
  hyperfang
  hypervoice
  hyperspacefury
  hyperspacehole
  hypnosis
  iceball
  icebeam
  iceburn
  icefang
  icehammer
  icepunch
  iceshard
  iciclecrash
  iciclespear
  icywind
  imprison
  incinerate
  inferno
  infernooverdrive
  infestation
  ingrain
  instruct
  iondeluge
  irondefense
  ironhead
  irontail
  jawlock
  judgment
  jumpkick
  karatechop
  kinesis
  kingsshield
  knockoff
  landswrath
  laserfocus
  lastresort
  lavaplume
  leafblade
  leafstorm
  leaftornado
  leafage
  leechlife
  leechseed
  leer
  letssnuggleforever
  lick
  lightscreen
  lightthatburnsthesky
  lifedew
  lightofruin
  liquidation
  lockon
  lovelykiss
  lowkick
  lowsweep
  luckychant
  lunardance
  lunge
  lusterpurge
  machpunch
  magiccoat
  magicpowder
  magicroom
  magicalleaf
  magikarpsrevenge
  magmastorm
  magnetbomb
  magnetrise
  magneticflux
  magnitude
  maliciousmoonsault
  matblock
  mefirst
  maxairstream
  maxdarkness
  maxflare
  maxflutterby
  maxgeyser
  maxguard
  meanlook
  maxhailstorm
  maxknuckle
  maxlightning
  maxmindstorm
  maxooze
  maxovergrowth
  maxphantasm
  maxquake
  maxrockfall
  maxstarfall
  maxsteelspike
  maxstrike
  maxwyrmwind
  meditate
  megadrain
  megakick
  megapunch
  megahorn
  memento
  menacingmoonrazemaelstrom
  metalburst
  metalclaw
  metalsound
  meteorassault
  meteormash
  metronome
  milkdrink
  mimic
  mindblown
  mindreader
  minimize
  miracleeye
  mirrorcoat
  mirrormove
  mirrorshot
  mist
  mistball
  mistyterrain
  moonblast
  moongeistbeam
  moonlight
  morningsun
  mudbomb
  mudshot
  mudsport
  mudslap
  muddywater
  multiattack
  mysticalfire
  nastyplot
  naturalgift
  naturepower
  naturesmadness
  needlearm
  neverendingnightmare
  nightdaze
  nightshade
  nightslash
  nightmare
  nobleroar
  noretreat
  nuzzle
  oblivionwing
  obstruct
  oceanicoperetta
  octazooka
  octolock
  odorsleuth
  ominouswind
  originpulse
  outrage
  overdrive
  overheat
  painsplit
  paleowave
  paraboliccharge
  partingshot
  payday
  payback
  peck
  perishsong
  petalblizzard
  petaldance
  phantomforce
  photongeyser
  pikapapow
  pinmissile
  plasmafists
  playnice
  playrough
  pluck
  poisonfang
  poisongas
  poisonjab
  poisonpowder
  poisonsting
  poisontail
  pollenpuff
  pound
  powder
  powdersnow
  powergem
  powersplit
  powerswap
  powertrick
  powertrip
  powerwhip
  poweruppunch
  precipiceblades
  present
  prismaticlaser
  protect
  psybeam
  psychup
  psychic
  psychicfangs
  psychicterrain
  psychoboost
  psychocut
  psychoshift
  psyshock
  psystrike
  psywave
  pulverizingpancake
  punishment
  purify
  pursuit
  pyroball
  quash
  quickattack
  quickguard
  quiverdance
  rage
  ragepowder
  raindance
  rapidspin
  razorleaf
  razorshell
  razorwind
  recover
  recycle
  reflect
  reflecttype
  refresh
  relicsong
  rest
  retaliate
  return
  revelationdance
  revenge
  reversal
  roar
  roaroftime
  rockblast
  rockclimb
  rockpolish
  rockslide
  rocksmash
  rockthrow
  rocktomb
  rockwrecker
  roleplay
  rollingkick
  rollout
  roost
  rototiller
  round
  sacredfire
  sacredsword
  safeguard
  sandattack
  sandtomb
  sandstorm
  sappyseed
  savagespinout
  scald
  scaryface
  scratch
  screech
  searingshot
  searingsunrazesmash
  secretpower
  secretsword
  seedbomb
  seedflare
  seismictoss
  selfdestruct
  shadowball
  shadowbone
  shadowclaw
  shadowforce
  shadowpunch
  shadowsneak
  shadowstrike
  sharpen
  shatteredpsyche
  sheercold
  shellsmash
  shelltrap
  shiftgear
  shockwave
  shoreup
  signalbeam
  silverwind
  simplebeam
  sing
  sinisterarrowraid
  sizzlyslide
  sketch
  skillswap
  skullbash
  skyattack
  skydrop
  skyuppercut
  slackoff
  slam
  slash
  sleeppowder
  sleeptalk
  sludge
  sludgebomb
  sludgewave
  smackdown
  smartstrike
  smellingsalts
  smog
  smokescreen
  snaptrap
  snarl
  snatch
  snipeshot
  snore
  soak
  softboiled
  solarbeam
  solarblade
  sonicboom
  soulstealing7starstrike
  spacialrend
  spark
  sparklingaria
  sparklyswirl
  spectralthief
  speedswap
  spiderweb
  spikecannon
  spikes
  spikyshield
  spiritbreak
  spiritshackle
  spitup
  spite
  splash
  splinteredstormshards
  splishysplash
  spore
  spotlight
  stealthrock
  steameruption
  steamroller
  steelbeam
  steelwing
  stickyweb
  stockpile
  stokedsparksurfer
  stomp
  stompingtantrum
  stoneedge
  storedpower
  stormthrow
  strangesteam
  strength
  strengthsap
  stringshot
  struggle
  strugglebug
  stuffcheeks
  stunspore
  submission
  substitute
  subzeroslammer
  suckerpunch
  sunnyday
  sunsteelstrike
  superfang
  superpower
  supersonic
  supersonicskystrike
  surf
  swagger
  swallow
  sweetkiss
  sweetscent
  swift
  switcheroo
  swordsdance
  synchronoise
  synthesis
  tackle
  tailglow
  tailslap
  tailwhip
  tailwind
  takedown
  tarshot
  taunt
  tearfullook
  teatime
  technoblast
  tectonicrage
  teeterdance
  telekinesis
  teleport
  thief
  thousandarrows
  thousandwaves
  thrash
  throatchop
  thunder
  thunderfang
  thunderpunch
  thundershock
  thunderwave
  thunderbolt
  tickle
  topsyturvy
  torment
  toxic
  toxicspikes
  toxicthread
  transform
  triattack
  trick
  trickroom
  trickortreat
  triplekick
  tropkick
  trumpcard
  twineedle
  twinkletackle
  twister
  uturn
  uproar
  vcreate
  vacuumwave
  veeveevolley
  venomdrench
  venoshock
  vinewhip
  visegrip
  vitalthrow
  voltswitch
  volttackle
  wakeupslap
  watergun
  waterpledge
  waterpulse
  watershuriken
  watersport
  waterspout
  waterfall
  weatherball
  whirlpool
  whirlwind
  wideguard
  wildcharge
  willowisp
  wingattack
  wish
  withdraw
  wonderroom
  woodhammer
  workup
  worryseed
  wrap
  wringout
  xscissor
  yawn
  zapcannon
  zenheadbutt
  zingzap
  zippyzap
}

# The supported Pokémon
enum Pokemon {
  bulbasaur
  ivysaur
  venusaur
  venusaurmega
  charmander
  charmeleon
  charizard
  charizardmegax
  charizardmegay
  charizardgmax
  squirtle
  wartortle
  blastoise
  blastoisemega
  caterpie
  metapod
  butterfree
  butterfreegmax
  weedle
  kakuna
  beedrill
  beedrillmega
  pidgey
  pidgeotto
  pidgeot
  pidgeotmega
  rattata
  rattataalola
  raticate
  raticatealola
  raticatealolatotem
  spearow
  fearow
  ekans
  arbok
  pikachu
  pikachugmax
  pikachucosplay
  pikachurockstar
  pikachubelle
  pikachupopstar
  pikachuphd
  pikachulibre
  pikachuoriginal
  pikachuhoenn
  pikachusinnoh
  pikachuunova
  pikachukalos
  pikachualola
  pikachupartner
  pikachustarter
  raichu
  raichualola
  sandshrew
  sandshrewalola
  sandslash
  sandslashalola
  nidoranf
  nidorina
  nidoqueen
  nidoranm
  nidorino
  nidoking
  clefairy
  clefable
  vulpix
  vulpixalola
  ninetales
  ninetalesalola
  jigglypuff
  wigglytuff
  zubat
  golbat
  oddish
  gloom
  vileplume
  paras
  parasect
  venonat
  venomoth
  diglett
  diglettalola
  dugtrio
  dugtrioalola
  meowth
  meowthalola
  meowthgalar
  meowthgmax
  persian
  persianalola
  psyduck
  golduck
  mankey
  primeape
  growlithe
  arcanine
  poliwag
  poliwhirl
  poliwrath
  abra
  kadabra
  alakazam
  alakazammega
  machop
  machoke
  machamp
  machampgmax
  bellsprout
  weepinbell
  victreebel
  tentacool
  tentacruel
  geodude
  geodudealola
  graveler
  graveleralola
  golem
  golemalola
  ponyta
  ponytagalar
  rapidash
  rapidashgalar
  slowpoke
  slowpokegalar
  slowbro
  slowbromega
  magnemite
  magneton
  farfetchd
  farfetchdgalar
  doduo
  dodrio
  seel
  dewgong
  grimer
  grimeralola
  muk
  mukalola
  shellder
  cloyster
  gastly
  haunter
  gengar
  gengarmega
  gengarmax
  onix
  drowzee
  hypno
  krabby
  kingler
  kinglergmax
  voltorb
  electrode
  exeggcute
  exeggutor
  exeggutoralola
  cubone
  marowak
  marowakalola
  marowakalolatotem
  hitmonlee
  hitmonchan
  lickitung
  koffing
  weezing
  weezinggalar
  rhyhorn
  rhydon
  chansey
  tangela
  kangaskhan
  kangaskhanmega
  horsea
  seadra
  goldeen
  seaking
  staryu
  starmie
  mrmime
  mrmimegalar
  scyther
  jynx
  electabuzz
  magmar
  pinsir
  pinsirmega
  tauros
  magikarp
  gyarados
  gyaradosmega
  lapras
  laprasgmax
  ditto
  eevee
  eeveestarter
  eeveegmax
  vaporeon
  jolteon
  flareon
  porygon
  omanyte
  omastar
  kabuto
  kabutops
  aerodactyl
  aerodactylmega
  snorlax
  snorlaxgmax
  articuno
  zapdos
  moltres
  dratini
  dragonair
  dragonite
  mewtwo
  mewtwomegax
  mewtwomegay
  mew
  chikorita
  bayleef
  meganium
  cyndaquil
  quilava
  typhlosion
  totodile
  croconaw
  feraligatr
  sentret
  furret
  hoothoot
  noctowl
  ledyba
  ledian
  spinarak
  ariados
  crobat
  chinchou
  lanturn
  pichu
  pichuspikyeared
  cleffa
  igglybuff
  togepi
  togetic
  natu
  xatu
  mareep
  flaaffy
  ampharos
  ampharosmega
  bellossom
  marill
  azumarill
  sudowoodo
  politoed
  hoppip
  skiploom
  jumpluff
  aipom
  sunkern
  sunflora
  yanma
  wooper
  quagsire
  espeon
  umbreon
  murkrow
  slowking
  misdreavus
  unown
  wobbuffet
  girafarig
  pineco
  forretress
  dunsparce
  gligar
  steelix
  steelixmega
  snubbull
  granbull
  qwilfish
  scizor
  scizormega
  shuckle
  heracross
  heracrossmega
  sneasel
  teddiursa
  ursaring
  slugma
  magcargo
  swinub
  piloswine
  corsola
  corsolagalar
  remoraid
  octillery
  delibird
  mantine
  skarmory
  houndour
  houndoom
  houndoommega
  kingdra
  phanpy
  donphan
  porygon2
  stantler
  smeargle
  tyrogue
  hitmontop
  smoochum
  elekid
  magby
  miltank
  blissey
  raikou
  entei
  suicune
  larvitar
  pupitar
  tyranitar
  tyranitarmega
  lugia
  hooh
  celebi
  treecko
  grovyle
  sceptile
  sceptilemega
  torchic
  combusken
  blaziken
  blazikenmega
  mudkip
  marshtomp
  swampert
  swampertmega
  poochyena
  mightyena
  zigzagoon
  zigzagoongalar
  linoone
  linoonegalar
  wurmple
  silcoon
  beautifly
  cascoon
  dustox
  lotad
  lombre
  ludicolo
  seedot
  nuzleaf
  shiftry
  taillow
  swellow
  wingull
  pelipper
  ralts
  kirlia
  gardevoir
  gardevoirmega
  surskit
  masquerain
  shroomish
  breloom
  slakoth
  vigoroth
  slaking
  nincada
  ninjask
  shedinja
  whismur
  loudred
  exploud
  makuhita
  hariyama
  azurill
  nosepass
  skitty
  delcatty
  sableye
  sableyemega
  mawile
  mawilemega
  aron
  lairon
  aggron
  aggronmega
  meditite
  medicham
  medichammega
  electrike
  manectric
  manectricmega
  plusle
  minun
  volbeat
  illumise
  roselia
  gulpin
  swalot
  carvanha
  sharpedo
  sharpedomega
  wailmer
  wailord
  numel
  camerupt
  cameruptmega
  torkoal
  spoink
  grumpig
  spinda
  trapinch
  vibrava
  flygon
  cacnea
  cacturne
  swablu
  altaria
  altariamega
  zangoose
  seviper
  lunatone
  solrock
  barboach
  whiscash
  corphish
  crawdaunt
  baltoy
  claydol
  lileep
  cradily
  anorith
  armaldo
  feebas
  milotic
  castform
  castformsunny
  castformrainy
  castformsnowy
  kecleon
  shuppet
  banette
  banettemega
  duskull
  dusclops
  tropius
  chimecho
  absol
  absolmega
  wynaut
  snorunt
  glalie
  glaliemega
  spheal
  sealeo
  walrein
  clamperl
  huntail
  gorebyss
  relicanth
  luvdisc
  bagon
  shelgon
  salamence
  salamencemega
  beldum
  metang
  metagross
  metagrossmega
  regirock
  regice
  registeel
  latias
  latiasmega
  latios
  latiosmega
  kyogre
  kyogreprimal
  groudon
  groudonprimal
  rayquaza
  rayquazamega
  jirachi
  deoxys
  deoxysattack
  deoxysdefense
  deoxysspeed
  turtwig
  grotle
  torterra
  chimchar
  monferno
  infernape
  piplup
  prinplup
  empoleon
  starly
  staravia
  staraptor
  bidoof
  bibarel
  kricketot
  kricketune
  shinx
  luxio
  luxray
  budew
  roserade
  cranidos
  rampardos
  shieldon
  bastiodon
  burmy
  wormadam
  wormadamsandy
  wormadamtrash
  mothim
  combee
  vespiquen
  pachirisu
  buizel
  floatzel
  cherubi
  cherrim
  cherrimsunshine
  shellos
  shelloseast
  gastrodon
  gastrodoneast
  ambipom
  drifloon
  drifblim
  buneary
  lopunny
  lopunnymega
  mismagius
  honchkrow
  glameow
  purugly
  chingling
  stunky
  skuntank
  bronzor
  bronzong
  bonsly
  mimejr
  happiny
  chatot
  spiritomb
  gible
  gabite
  garchomp
  garchompmega
  munchlax
  riolu
  lucario
  lucariomega
  hippopotas
  hippowdon
  skorupi
  drapion
  croagunk
  toxicroak
  carnivine
  finneon
  lumineon
  mantyke
  snover
  abomasnow
  abomasnowmega
  weavile
  magnezone
  lickilicky
  rhyperior
  tangrowth
  electivire
  magmortar
  togekiss
  yanmega
  leafeon
  glaceon
  gliscor
  mamoswine
  porygonz
  gallade
  gallademega
  probopass
  dusknoir
  froslass
  rotom
  rotomheat
  rotomwash
  rotomfrost
  rotomfan
  rotommow
  uxie
  mesprit
  azelf
  dialga
  palkia
  heatran
  regigigas
  giratina
  giratinaorigin
  cresselia
  phione
  manaphy
  darkrai
  shaymin
  shayminsky
  arceus
  arceusbug
  arceusdark
  arceusdragon
  arceuselectric
  arceusfairy
  arceusfighting
  arceusfire
  arceusflying
  arceusghost
  arceusgrass
  arceusground
  arceusice
  arceuspoison
  arceuspsychic
  arceusrock
  arceussteel
  arceuswater
  victini
  snivy
  servine
  serperior
  tepig
  pignite
  emboar
  oshawott
  dewott
  samurott
  patrat
  watchog
  lillipup
  herdier
  stoutland
  purrloin
  liepard
  pansage
  simisage
  pansear
  simisear
  panpour
  simipour
  munna
  musharna
  pidove
  tranquill
  unfezant
  blitzle
  zebstrika
  roggenrola
  boldore
  gigalith
  woobat
  swoobat
  drilbur
  excadrill
  audino
  audinomega
  timburr
  gurdurr
  conkeldurr
  tympole
  palpitoad
  seismitoad
  throh
  sawk
  sewaddle
  swadloon
  leavanny
  venipede
  whirlipede
  scolipede
  cottonee
  whimsicott
  petilil
  lilligant
  basculin
  basculinbluestriped
  sandile
  krokorok
  krookodile
  darumaka
  darumakagalar
  darmanitan
  darmanitangalar
  darmanitanzen
  darmanitangalarzen
  maractus
  dwebble
  crustle
  scraggy
  scrafty
  sigilyph
  yamask
  yamaskgalar
  cofagrigus
  tirtouga
  carracosta
  archen
  archeops
  trubbish
  garbodor
  garbodorgmax
  zorua
  zoroark
  minccino
  cinccino
  gothita
  gothorita
  gothitelle
  solosis
  duosion
  reuniclus
  ducklett
  swanna
  vanillite
  vanillish
  vanilluxe
  deerling
  sawsbuck
  emolga
  karrablast
  escavalier
  foongus
  amoonguss
  frillish
  frillishfemale
  jellicent
  jellicentfemale
  alomomola
  joltik
  galvantula
  ferroseed
  ferrothorn
  klink
  klang
  klinklang
  tynamo
  eelektrik
  eelektross
  elgyem
  beheeyem
  litwick
  lampent
  chandelure
  axew
  fraxure
  haxorus
  cubchoo
  beartic
  cryogonal
  shelmet
  accelgor
  stunfisk
  stunfiskgalar
  mienfoo
  mienshao
  druddigon
  golett
  golurk
  pawniard
  bisharp
  bouffalant
  rufflet
  braviary
  vullaby
  mandibuzz
  heatmor
  durant
  deino
  zweilous
  hydreigon
  larvesta
  volcarona
  cobalion
  terrakion
  virizion
  tornadus
  tornadustherian
  thundurus
  thundurustherian
  reshiram
  zekrom
  landorus
  landorustherian
  kyurem
  kyuremblack
  kyuremwhite
  keldeo
  keldeoresolute
  meloetta
  meloettapirouette
  genesect
  genesectdouse
  genesectshock
  genesectburn
  genesectchill
  chespin
  quilladin
  chesnaught
  fennekin
  braixen
  delphox
  froakie
  frogadier
  greninja
  greninjaash
  bunnelby
  diggersby
  fletchling
  fletchinder
  talonflame
  scatterbug
  spewpa
  vivillon
  vivillonfancy
  vivillonpokeball
  litleo
  pyroar
  flabebe
  floette
  floetteeternal
  florges
  skiddo
  gogoat
  pancham
  pangoro
  furfrou
  espurr
  meowstic
  meowsticf
  honedge
  doublade
  aegislash
  aegislashblade
  spritzee
  aromatisse
  swirlix
  slurpuff
  inkay
  malamar
  binacle
  barbaracle
  skrelp
  dragalge
  clauncher
  clawitzer
  helioptile
  heliolisk
  tyrunt
  tyrantrum
  amaura
  aurorus
  sylveon
  hawlucha
  dedenne
  carbink
  goomy
  sliggoo
  goodra
  klefki
  phantump
  trevenant
  pumpkaboo
  pumpkaboosmall
  pumpkaboolarge
  pumpkaboosuper
  gourgeist
  gourgeistsmall
  gourgeistlarge
  gourgeistsuper
  bergmite
  avalugg
  noibat
  noivern
  xerneas
  yveltal
  zygarde
  zygarde10
  zygardecomplete
  diancie
  dianciemega
  hoopa
  hoopaunbound
  volcanion
  rowlet
  dartrix
  decidueye
  litten
  torracat
  incineroar
  popplio
  brionne
  primarina
  pikipek
  trumbeak
  toucannon
  yungoos
  gumshoos
  gumshoostotem
  grubbin
  charjabug
  vikavolt
  vikavolttotem
  crabrawler
  crabominable
  oricorio
  oricoriopompom
  oricoriopau
  oricoriosensu
  cutiefly
  ribombee
  ribombeetotem
  rockruff
  lycanroc
  lycanrocmidnight
  lycanrocdusk
  wishiwashi
  wishiwashischool
  mareanie
  toxapex
  mudbray
  mudsdale
  dewpider
  araquanid
  araquanidtotem
  fomantis
  lurantis
  lurantistotem
  morelull
  shiinotic
  salandit
  salazzle
  salazzletotem
  stufful
  bewear
  bounsweet
  steenee
  tsareena
  comfey
  oranguru
  passimian
  wimpod
  golisopod
  sandygast
  palossand
  pyukumuku
  typenull
  silvally
  silvallybug
  silvallydark
  silvallydragon
  silvallyelectric
  silvallyfairy
  silvallyfighting
  silvallyfire
  silvallyflying
  silvallyghost
  silvallygrass
  silvallyground
  silvallyice
  silvallypoison
  silvallypsychic
  silvallyrock
  silvallysteel
  silvallywater
  minior
  miniormeteor
  komala
  turtonator
  togedemaru
  togedemarutotem
  mimikyu
  mimikyubusted
  mimikyutotem
  mimikyubustedtotem
  bruxish
  drampa
  dhelmise
  jangmoo
  hakamoo
  kommoo
  kommoototem
  tapukoko
  tapulele
  tapubulu
  tapufini
  cosmog
  cosmoem
  solgaleo
  lunala
  nihilego
  buzzwole
  pheromosa
  xurkitree
  celesteela
  kartana
  guzzlord
  necrozma
  necrozmaduskmane
  necrozmadawnwings
  necrozmaultra
  magearna
  magearnaoriginal
  marshadow
  poipole
  naganadel
  stakataka
  blacephalon
  zeraora
  missingno
  meltan
  melmetal
  melmetalgmax
  grookey
  thwackey
  rillaboom
  scorbunny
  raboot
  cinderace
  sobble
  drizzile
  inteleon
  skwovet
  greedent
  rookidee
  corvisquire
  corviknight
  corviknightgmax
  blipbug
  dottler
  orbeetle
  orbeetlegmax
  nickit
  thievul
  gossifleur
  eldegoss
  wooloo
  dubwool
  chewtle
  drednaw
  drednawgmax
  yamper
  boltund
  rolycoly
  carkol
  coalossal
  coalossalgmax
  applin
  flapple
  flapplegmax
  appletun
  appletungmax
  silicobra
  sandaconda
  sandacondagmax
  cramorant
  cramorantgulping
  cramorantgorging
  arrokuda
  barraskewda
  toxel
  toxtricity
  toxtricitylowkey
  toxtricitygmax
  toxtricitylowkeygmax
  sizzlipede
  centiskorch
  centiskorchgmax
  clobbopus
  grapploct
  sinistea
  sinisteachipped
  polteageist
  polteageistchipped
  hatenna
  hattrem
  hatterene
  hatterenegmax
  impidimp
  morgrem
  grimmsnarl
  grimmsnarlgmax
  obstagoon
  perrserker
  cursola
  sirfetchd
  mrrime
  runerigus
  milcery
  alcremie
  alcremiegmax
  falinks
  pincurchin
  snom
  frosmoth
  stonjourner
  eiscue
  eiscuenoice
  indeedee
  indeedeef
  morpeko
  morpekohangry
  cufant
  copperajah
  copperajahgmax
  dracozolt
  arctozolt
  dracovish
  arctovish
  duraludon
  duraludongmax
  dreepy
  drakloak
  dragapult
  zacian
  zaciancrowned
  zamazenta
  zamazentacrowned
  eternatus
  eternatuseternamax
  syclant
  revenankh
  pyroak
  fidgit
  stratagem
  arghonaut
  kitsunoh
  cyclohm
  colossoil
  krilowatt
  voodoom
  tomohawk
  necturna
  mollux
  aurumoth
  malaconda
  cawmodore
  volkraken
  plasmanta
  naviathan
  crucibelle
  crucibellemega
  kerfluffle
  pajantom
  jumbao
  caribolt
  smokomodo
  snaelstrom
  equilibra
  syclar
  embirch
  flarelm
  breezi
  scratchet
  necturine
  cupra
  argalis
  brattler
  cawdet
  volkritter
  snugglow
  floatoy
  caimanoe
  pluffle
  rebble
  tactite
  privatyke
  voodoll
  mumbao
  fawnifer
  electrelk
  smogecko
  smoguana
  swirlpool
  coribalis
  pokestarsmeargle
  pokestarufo
  pokestarufo2
  pokestarbrycenman
  pokestarmt
  pokestarmt2
  pokestartransport
  pokestargiant
  pokestarhumanoid
  pokestarmonster
  pokestarf00
  pokestarf002
  pokestarspirit
  pokestarblackdoor
  pokestarwhitedoor
  pokestarblackbelt
  pokestarufopropu2
}

type Query {
  # Gets details on a single ability based on a fuzzy search.You can supply skip
  # and take to paginate the fuzzy search and reverse to show the least likely
  # matched on top.Reversal is applied before pagination!
  getAbilityDetailsByFuzzy(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The ability to look up
    ability: String!
  ): AbilityEntry!
  # Gets details on a single ability based on an exact name match.
  getAbilityDetailsByName(ability: Abilities!): AbilityEntry!
  # Gets raw entries of multiple ability based on a fuzzy search.You can supply
  # skip and take to limit the amount of flavour texts to return and reverse to
  # show latest games on top.Reversal is applied before pagination!
  getAbilityByFuzzy(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The ability to look up
    ability: String!
  ): [JSONObject!]!
  # Gets the raw entry of a single ability by name.
  getAbilityByName(ability: Abilities!): JSONObject!
  # Gets details on a single Pokémon based on species name.You can supply skip and
  # take to limit the amount of flavour texts to return and reverse to show latest
  # games on top.Reversal is applied before pagination!
  getPokemonDetails(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The pokemon to look up
    pokemon: Pokemon!
  ): DexDetails!
  # Gets details on a single Pokémon based on species name.You can supply skip and
  # take to limit the amount of flavour texts to return and reverse to show latest
  # games on top.Reversal is applied before pagination!
  getPokemonDetailsByName(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The pokemon to look up
    pokemon: Pokemon!
  ): DexDetails!
  # Gets details on a single Pokémon based on a fuzzy search.You can supply skip
  # and take to limit the amount of flavour texts to return and reverse to show
  # latest games on top.Reversal is applied before pagination!
  getPokemonDetailsByFuzzy(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The Pokémon to look up
    pokemon: String!
  ): DexDetails!
  # Gets dex entries for Pokémon based on a fuzzy searchYou can supply a skip and
  # take to paginate the results and reverse to show the results least to most
  # well matchesReversal is applied before pagination!
  getDexEntries(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The Pokémon to look up
    pokemon: String!
  ): [DexEntry!]!
  # Gets the dex entry for a Pokémon based on their species name
  getDexEntryBySpeciesName(pokemon: Pokemon!): JSONObject!
  # Gets the dex entry for a Pokémon based on their dex number
  getDexEntryByDexNumber(num: Float!): JSONObject!
  # Gets details on a single item based on a fuzzy search.You can supply skip and
  # take to paginate the fuzzy search and reverse to show teh least likely results
  # on topReversal is applied before paginations!
  getItemDetailsByFuzzy(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The item to look up
    item: String!
  ): ItemEntry!
  # Gets details on a single item based on an exact name match.
  getItemDetailsByName(item: Items!): ItemEntry!
  # Gets raw entries of multiple items based on a fuzzy search.You can supply skip
  # and take to limit the amount of flavour texts to return and reverse to show
  # latest games on top.Reversal is applied before pagination!
  getItemByFuzzy(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The item to look up
    item: String!
  ): [JSONObject!]!
  # Gets the raw entry of a single item based on name.
  getItemByName(item: Items!): JSONObject!
  # Gets the learnsets for a given Pokémon and move.Multiple moves are possible by
  # putting them in an array: [move1, move2].You can also apply a generation
  # filter (only results for the given generation will be returned) with the
  # generation argument
  getPokemonLearnset(
    # The Pokémon for which to get the learnset
    pokemon: Pokemon!
    # The moves to match against the Pokémon
    moves: [Moves!]!
    # The generation filter to apply
    generation: Int
  ): LearnsetEntry!
  # Gets the learnset for a given Pokémon and move.A fuzzy search is performed to
  # find a matching Pokémon and moveMultiple moves are possible by putting them in
  # an array: [move1, move2].You can also apply a generation filter (only results
  # for the given generation will be returned) with the generation argument
  getPokemonLearnsetByFuzzy(
    # The Pokémon for which to get the learnset
    pokemon: String!
    # The moves to match against the Pokémon
    moves: [String!]!
    # The generation filter to apply
    generation: Int
  ): LearnsetEntry!
  # Gets details on a single move based on a fuzzy search.You can supply skip and
  # take to paginate the fuzzy search and reverse to show teh least likely results
  # on topReversal is applied before paginations!
  getMoveDetailsByFuzzy(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The move to look up
    move: String!
  ): MoveEntry!
  # Gets details on a single move based on an exact name match.
  getMoveDetailsByName(move: Moves!): MoveEntry!
  # Gets raw entries of multiple moves based on a fuzzy search.You can supply skip
  # and take to limit the amount of flavour texts to return and reverse to show
  # latest games on top.Reversal is applied before pagination!
  getMoveByFuzzy(
    # Sets the offset where to start
    skip: Int = 0
    # Return only this many results, starting from the offset
    take: Int = 10
    # Reverses the dataset before paginating
    reverse: Boolean = false
    # The move to look up
    move: String!
  ): [JSONObject!]!
  # Gets the raw entry of a single move based on name.
  getMoveByName(move: Moves!): JSONObject!
  # Gets the type matchup data for the given type or types
  getTypeMatchup(
    # The types to check
    types: [Types!]!
  ): TypeMatchups!
  # Gets the raw type matchup data for any one given type
  getTypeByName(type: Types!): JSONObject!
}

# A Pokémon's stats
type StatsEntry {
  # The base HP stat of a pokemon
  hp: Int!
  # The base attack stat of a Pokémon
  attack: Int!
  # The base defense stat of a Pokémon
  defense: Int!
  # The base special attack stat of a Pokémon
  specialattack: Int!
  # The base special defense stat of a Pokémon
  specialdefense: Int!
  # The base speed stat of a Pokémon
  speed: Int!
}

# A type matchup entry
type TypeEntry {
  # The types with 4x effectiveness
  doubleEffectiveTypes: [String!]!
  # The types with 2x effectiveness
  effectiveTypes: [String!]!
  # The types with 1x effectiveness
  normalTypes: [String!]!
  # The types with 0.5x effectiveness
  resistedTypes: [String!]!
  # The types with 0.25x effectiveness
  doubleResistedTypes: [String!]!
  # The types with 0x effectiveness
  effectlessTypes: [String!]!
}

# The type matchups for any one or two given types
type TypeMatchups {
  # The type matchups when attacking
  attacking: TypeEntry!
  # The type matchups when defending
  defending: TypeEntry!
}

# The types in Pokémon
enum Types {
  bug
  dark
  dragon
  electric
  fairy
  fighting
  fire
  flying
  ghost
  grass
  ground
  ice
  normal
  poison
  psychic
  rock
  steel
  water
}

