/**
 * Replace the residual HTML tags from the code.
 * @since 3.0.0
 * @param {string} text The text to parse
 * @returns {string}
 */
module.exports = (text) => text.replace(/(?:&(\w{3,7});)|(?:<(\w{1,4}) ?\/?>)/g,
	(match, entity, html) => {
		if (entity) return module.exports.ENTITIES[entity] || entity;
		if (html) return module.exports.HTML_TAGS[html] || html;
		return match;
	}).replace(/(\s){2,}/g, '$1');

module.exports.HTML_TAGS = {
	html: '',
	body: '',
	h1: '**',
	h2: '**',
	h3: '**',
	h4: '*',
	h5: '*',
	h6: '*',
	p: '\n',
	pre: '```',
	div: '\n',
	br: '\n'
};

/**
 * @link https://www.toptal.com/designers/htmlarrows/punctuation/
 */
module.exports.ENTITIES = {
	// Punctuation
	excl: '!',
	quot: '"',
	num: '#',
	percnt: '%',
	amp: '&',
	apos: '\'',
	lpar: '(',
	rpar: ')',
	ast: '*',
	comma: ',',
	period: '.',
	sol: '/',
	colon: ':',
	semi: ';',
	quest: '?',
	commat: '@',
	lbrack: '[',
	bsol: '\\',
	rbrack: ']',
	Hat: '^',
	lowbar: '_',
	grave: '`',
	lbrace: '{',
	vert: '|',
	rbrace: '}',
	tilde: '~',
	nbsp: ' ',
	iexcl: '¡',
	brvbar: '¦',
	sect: '§',
	uml: '¨',
	copy: '©',
	ordf: 'ª',
	laquo: '«',
	not: '¬',
	shy: '',
	reg: '®',
	macr: '¯',
	sup2: '²',
	sup3: '³',
	acute: '´',
	micro: 'µ',
	para: '¶',
	middot: '·',
	cedil: '¸',
	sup1: '¹',
	ordm: 'º',
	raquo: '»',
	iquest: '¿',
	hyphen: '‐',
	ndash: '–',
	mdash: '—',
	horbar: '―',
	Vert: '‖',
	lsquo: '‘',
	rsquo: '’',
	sbquo: '‚',
	ldquo: '“',
	rdquo: '”',
	bdquo: '„',
	dagger: '†',
	Dagger: '‡',
	bull: '•',
	nldr: '‥',
	hellip: '…',
	permil: '‰',
	pertenk: '‱',
	prime: '′',
	Prime: '″',
	tprime: '‴',
	bprime: '‵',
	lsaquo: '‹',
	rsaquo: '›',
	oline: '‾',
	caret: '⁁',
	hybull: '⁃',
	frasl: '⁄',
	bsemi: '⁏',
	qprime: '⁗',
	trade: '™',

	// Numbers
	frac14: '¼',
	frac12: '½',
	frac34: '¾',
	frac13: '⅓',
	frac23: '⅔',
	frac15: '⅕',
	frac25: '⅖',
	frac35: '⅗',
	frac45: '⅘',
	frac16: '⅙',
	frac56: '⅚',
	frac18: '⅛',
	frac38: '⅜',
	frac58: '⅝',
	frac78: '⅞',

	// Letters
	Agrave: 'À',
	Aacute: 'Á',
	Acirc: 'Â',
	Atilde: 'Ã',
	Auml: 'Ä',
	Aring: 'Å',
	AElig: 'Æ',
	Ccedil: 'Ç',
	Egrave: 'È',
	Eacute: 'É',
	Ecirc: 'Ê',
	Euml: 'Ë',
	Lgrave: 'Ì',
	Lacute: 'Í',
	Lcirc: 'Î',
	Luml: 'Ï',
	ETH: 'Ð',
	Ntilde: 'Ñ',
	Ograve: 'Ò',
	Oacute: 'Ó',
	Ocirc: 'Ô',
	Otilde: 'Õ',
	Ouml: 'Ö',
	Oslash: 'Ø',
	Ugrave: 'Ù',
	Uacute: 'Ú',
	Ucirc: 'Û',
	Uuml: 'Ü',
	Yacute: 'Ý',
	THORN: 'Þ',
	szlig: 'ß',
	agrave: 'à',
	aacute: 'á',
	acirc: 'â',
	atilde: 'ã',
	auml: 'ä',
	aring: 'å',
	aelig: 'æ',
	ccedil: 'ç',
	egrave: 'è',
	eacute: 'é',
	ecirc: 'ê',
	euml: 'ë',
	igrave: 'ì',
	iacute: 'í',
	icirc: 'î',
	iuml: 'ï',
	eth: 'ð',
	ntilde: 'ñ',
	// Omitted ~80

	// Currency
	dollar: '$',
	cent: '¢',
	pound: '£',
	euro: '€',
	yen: '¥',
	curren: '¤'
};
