export * as Birthday from './Birthday';
export * as Channels from './Channels';
export * as Events from './Events';
export * as Messages from './Messages';
export * as Music from './Music';
export * as Notifications from './Notifications/All';
export * as Permissions from './Permissions';
export * as Roles from './Roles';
export * as Selfmod from './Selfmod/All';
export * as Social from './Social';
export * as Starboard from './Starboard';
export * as Suggestions from './Suggestions';
export * as Trigger from './Trigger';

export const Prefix = 'prefix';
export const Language = 'language';
export const CustomCommands = 'customCommands';
export const CommandAutoDelete = 'commandAutoDelete';
export const DisabledChannels = 'disabledChannels';
export const DisabledCommands = 'disabledCommands';
export const DisabledCommandChannels = 'disabledCommandsChannels';
export const StickyRoles = 'stickyRoles';
export const ReactionRoles = 'reactionRoles';
