export * as Birthday from './Birthday.js';
export * as Channels from './Channels.js';
export * as Events from './Events.js';
export * as Messages from './Messages.js';
export * as Music from './Music.js';
export * as Notifications from './Notifications/All.js';
export * as Permissions from './Permissions.js';
export * as Roles from './Roles.js';
export * as Selfmod from './Selfmod/All.js';
export * as Social from './Social.js';
export * as Starboard from './Starboard.js';
export * as Suggestions from './Suggestions.js';
export * as Trigger from './Trigger.js';

export const Prefix = 'prefix';
export const Language = 'language';
export const CustomCommands = 'customCommands';
export const CommandAutoDelete = 'commandAutoDelete';
export const DisabledChannels = 'disabledChannels';
export const DisabledCommands = 'disabledCommands';
export const DisabledCommandChannels = 'disabledCommandsChannels';
export const StickyRoles = 'stickyRoles';
export const ReactionRoles = 'reactionRoles';
