import type { Song } from '@lib/structures/music/Song';
import type { ScheduleEntity } from '@orm/entities/ScheduleEntity';
import type { HungerGamesGame } from '@root/commands/Games/hungergames';
import type { LevelTitles } from '@root/commands/Social/level';
import type { ProfileTitles } from '@root/commands/Social/profile';
import type { StatsGeneral, StatsUptime, StatsUsage } from '@root/commands/System/stats';
import type { Moderation } from '@utils/constants';
import type { HungerGamesUsage } from '@utils/Games/HungerGamesUsage';
import type { LanguageHelpDisplayOptions } from '@utils/LanguageHelp';
import type { Guild, GuildMember, PermissionString, Role, User } from 'discord.js';
import type { SchemaEntry } from 'klasa';
import type { Kitsu } from './definitions/Kitsu';
import type { OverwatchRating } from './definitions/Overwatch';
import type { NotificationsStreamsTwitchEventStatus } from './settings/GuildSettings';

export const enum Position {
	Before,
	After
}

export const enum Filter {
	Attachments,
	Author,
	Bots,
	Humans,
	Invites,
	Links,
	None,
	Skyra,
	User
}

declare module 'klasa' {
	export interface LanguageKeys {
		DEFAULT: (params: { key: string }) => string;
		DEFAULT_LANGUAGE: string;
		SETTING_GATEWAY_KEY_NOEXT: (params: { key: string }) => string;
		SETTING_GATEWAY_CHOOSE_KEY: (params: { keys: string[] }) => string;
		SETTING_GATEWAY_UNCONFIGURABLE_FOLDER: string;
		SETTING_GATEWAY_UNCONFIGURABLE_KEY: (params: { key: string }) => string;
		SETTING_GATEWAY_MISSING_VALUE: (params: { entry: SchemaEntry; value: string }) => string;
		SETTING_GATEWAY_DUPLICATE_VALUE: (params: { entry: SchemaEntry; value: string }) => string;
		SETTING_GATEWAY_INVALID_FILTERED_VALUE: (params: { entry: SchemaEntry; value: unknown }) => string;
		RESOLVER_MULTI_TOO_FEW: (params: { name: string; min?: number }) => string;
		RESOLVER_INVALID_BOOL: (params: { name: string }) => string;
		RESOLVER_INVALID_CHANNEL: (params: { name: string }) => string;
		RESOLVER_INVALID_CUSTOM: (params: { name: string; type: string }) => string;
		RESOLVER_INVALID_DATE: (params: { name: string }) => string;
		RESOLVER_INVALID_DURATION: (params: { name: string }) => string;
		RESOLVER_INVALID_EMOJI: (params: { name: string }) => string;
		RESOLVER_INVALID_FLOAT: (params: { name: string }) => string;
		RESOLVER_INVALID_GUILD: (params: { name: string }) => string;
		RESOLVER_INVALID_INT: (params: { name: string }) => string;
		RESOLVER_INVALID_INVITE: (params: { name: string }) => string;
		RESOLVER_INVALID_WAGER: (params: { bet: number }) => string;
		RESOLVER_INVALID_LITERAL: (params: { name: string }) => string;
		RESOLVER_INVALID_MEMBER: (params: { name: string }) => string;
		RESOLVER_INVALID_MESSAGE: (params: { name: string }) => string;
		RESOLVER_INVALID_PIECE: (params: { name: string; piece: string }) => string;
		RESOLVER_INVALID_REGEX_MATCH: (params: { name: string; pattern: string }) => string;
		RESOLVER_INVALID_ROLE: (params: { name: string }) => string;
		RESOLVER_INVALID_STRING: (params: { name: string }) => string;
		RESOLVER_INVALID_TIME: (params: { name: string }) => string;
		RESOLVER_INVALID_URL: (params: { name: string }) => string;
		RESOLVER_INVALID_USER: (params: { name: string }) => string;
		RESOLVER_INVALID_SNOWFLAKE: (params: { name: string }) => string;
		RESOLVER_STRING_SUFFIX: string;
		RESOLVER_MINMAX_EXACTLY: (params: { name: string; min: number }) => string;
		RESOLVER_MINMAX_BOTH: (params: { name: string; min: number; max: number; inclusive: boolean }) => string;
		RESOLVER_MINMAX_MIN: (params: { name: string; min: number; inclusive: boolean }) => string;
		RESOLVER_MINMAX_MAX: (params: { name: string; max: number; inclusive: boolean }) => string;
		REACTIONHANDLER_PROMPT: string;
		COMMANDMESSAGE_MISSING: string;
		COMMANDMESSAGE_MISSING_REQUIRED: (params: { name: string }) => string;
		COMMANDMESSAGE_MISSING_OPTIONALS: (params: { possibles: string }) => string;
		COMMANDMESSAGE_NOMATCH: (params: { possibles: string }) => string;
		MONITOR_COMMAND_HANDLER_REPROMPT: (params: { tag: string; name: string; time: string; cancelOptions: readonly string[] }) => string;
		MONITOR_COMMAND_HANDLER_REPEATING_REPROMPT: (params: { tag: string; name: string; time: string; cancelOptions: readonly string[] }) => string;
		MONITOR_COMMAND_HANDLER_ABORTED: string;
		INHIBITOR_COOLDOWN: (params: { remaining: number }) => string;
		INHIBITOR_MISSING_BOT_PERMS: (params: { missing: string[] }) => string;
		INHIBITOR_NSFW: string;
		INHIBITOR_PERMISSIONS: string;
		INHIBITOR_REQUIRED_SETTINGS: (params: { settings: readonly string[] }) => string;
		INHIBITOR_RUNIN: (params: { type: string }) => string;
		INHIBITOR_RUNIN_NONE: (params: { name: string }) => string;
		INHIBITOR_DISABLED_GUILD: string;
		INHIBITOR_DISABLED_GLOBAL: string;
		// used to build a LanguageBuilder for extendedHelp
		SYSTEM_HELP_TITLES: {
			EXPLAINED_USAGE: string;
			POSSIBLE_FORMATS: string;
			EXAMPLES: string;
			REMINDERS: string;
		};
		COMMAND_BLACKLIST_DESCRIPTION: string;
		COMMAND_BLACKLIST_SUCCESS: (params: {
			usersAdded: readonly string[];
			usersRemoved: readonly string[];
			guildsAdded: readonly string[];
			guildsRemoved: readonly string[];
		}) => string;
		COMMAND_UNLOAD: (params: { type: string; name: string }) => string;
		COMMAND_UNLOAD_DESCRIPTION: string;
		COMMAND_TRANSFER_ERROR: string;
		COMMAND_TRANSFER_SUCCESS: (params: { type: string; name: string }) => string;
		COMMAND_TRANSFER_FAILED: (params: { type: string; name: string }) => string;
		COMMAND_TRANSFER_DESCRIPTION: string;
		COMMAND_RELOAD: (params: { type: string; name: string; time: string }) => string;
		COMMAND_RELOAD_ALL: (params: { type: string; time: string }) => string;
		COMMAND_RELOAD_EVERYTHING: (params: { time: string }) => string;
		COMMAND_RELOAD_FAILED: (params: { type: string; name: string }) => string;
		COMMAND_RELOAD_DESCRIPTION: string;
		COMMAND_REBOOT: string;
		COMMAND_REBOOT_DESCRIPTION: string;
		COMMAND_PING: string;
		COMMAND_PING_DESCRIPTION: string;
		COMMAND_PINGPONG: (params: { diff: string; ping: string }) => string;
		COMMAND_INFO_DESCRIPTION: string;
		COMMAND_HELP_DESCRIPTION: string;
		COMMAND_HELP_NO_EXTENDED: string;
		COMMAND_HELP_DM: string;
		COMMAND_HELP_NODM: string;
		COMMAND_HELP_ALL_FLAG: (params: { prefix: string }) => string;
		COMMAND_HELP_COMMAND_COUNT: (params: { n: number }) => string;
		COMMAND_ENABLE: (params: { type: string; name: string }) => string;
		COMMAND_ENABLE_DESCRIPTION: string;
		COMMAND_DISABLE: (params: { type: string; name: string }) => string;
		COMMAND_DISABLE_DESCRIPTION: string;
		COMMAND_DISABLE_WARN: string;
		COMMAND_CONF_NOKEY: string;
		COMMAND_CONF_NOVALUE: string;
		COMMAND_CONF_GUARDED: (params: { name: string }) => string;
		COMMAND_CONF_UPDATED: (params: { key: string; response: string }) => string;
		COMMAND_CONF_KEY_NOT_ARRAY: string;
		COMMAND_CONF_GET_NOEXT: (params: { key: string }) => string;
		COMMAND_CONF_GET: (params: { key: string; value: string }) => string;
		COMMAND_CONF_RESET: (params: { key: string; value: string }) => string;
		COMMAND_CONF_NOCHANGE: (params: { key: string }) => string;
		COMMAND_CONF_SERVER_DESCRIPTION: string;
		COMMAND_CONF_SERVER: (params: { key: string; list: string }) => string;
		COMMAND_CONF_USER_DESCRIPTION: string;
		COMMAND_CONF_USER: (params: { key: string; list: string }) => string;
		COMMAND_CONF_SETTING_NOT_SET: string;
		MESSAGE_PROMPT_TIMEOUT: string;
		TEXT_PROMPT_ABORT_OPTIONS: readonly string[];
		COMMAND_LOAD: (params: { time: string; type: string; name: string }) => string;
		COMMAND_LOAD_FAIL: string;
		COMMAND_LOAD_ERROR: (params: { type: string; name: string; error: string }) => string;
		COMMAND_LOAD_DESCRIPTION: string;
		ARGUMENT_RANGE_INVALID: (params: { name: string }) => string;
		ARGUMENT_RANGE_MAX: (params: { name: string; maximum: number }) => string;
		COMMAND_ADD_DESCRIPTION: string;
		COMMAND_ADD_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ADD_PLAYLIST: (params: { amount: number }) => string;
		COMMAND_ADD_SONG: (params: { title: string }) => string;
		COMMAND_CLEAR_DESCRIPTION: string;
		COMMAND_CLEAR_DENIED: string;
		COMMAND_CLEAR_SUCCESS: (params: { amount: number }) => string;
		COMMAND_JOIN_DESCRIPTION: string;
		COMMAND_JOIN_NO_MEMBER: string;
		COMMAND_JOIN_NO_VOICECHANNEL: string;
		COMMAND_JOIN_SUCCESS: (params: { channel: string }) => string;
		COMMAND_JOIN_VOICE_DIFFERENT: string;
		COMMAND_JOIN_VOICE_FULL: string;
		COMMAND_JOIN_VOICE_NO_CONNECT: string;
		COMMAND_JOIN_VOICE_NO_SPEAK: string;
		COMMAND_JOIN_VOICE_SAME: string;
		COMMAND_JOIN_FAILED: string;
		COMMAND_LEAVE_DESCRIPTION: string;
		COMMAND_LEAVE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LEAVE_SUCCESS: (params: { channel: string }) => string;
		COMMAND_PAUSE_DESCRIPTION: string;
		COMMAND_PAUSE_SUCCESS: string;
		COMMAND_PLAY_DESCRIPTION: string;
		COMMAND_PLAY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PLAY_END: string;
		COMMAND_PLAY_NEXT: (params: { title: string; requester: string }) => string;
		COMMAND_PLAY_QUEUE_PAUSED: (params: { song: string }) => string;
		COMMAND_PLAY_QUEUE_PLAYING: string;
		COMMAND_PLAY_QUEUE_EMPTY: string;
		COMMAND_PLAYING_DESCRIPTION: string;
		COMMAND_PLAYING_DURATION: (params: { duration: string }) => string;
		COMMAND_PLAYING_QUEUE_EMPTY: string;
		COMMAND_PLAYING_QUEUE_NOT_PLAYING: string;
		COMMAND_REPEAT_DESCRIPTION: string;
		COMMAND_REPEAT_SUCCESS: (params: { enabled: boolean }) => string;
		COMMAND_QUEUE_DESCRIPTION: string;
		COMMAND_QUEUE_LAST: string;
		COMMAND_QUEUE_TITLE: (params: { guildname: string }) => string;
		COMMAND_QUEUE_LINE: (params: { position: number; duration: string; title: string; url: string; requester: string }) => string;
		COMMAND_QUEUE_NOWPLAYING: (context: {
			duration: string | null;
			title: string;
			url: string;
			requester: string;
			timeRemaining: string | null;
		}) => string;
		COMMAND_QUEUE_NOWPLAYING_TITLE: string;
		COMMAND_QUEUE_TOTAL_TITLE: string;
		COMMAND_QUEUE_TOTAL: (params: { songs: number; remainingTime: string }) => string;
		COMMAND_QUEUE_EMPTY: string;
		COMMAND_QUEUE_DASHBOARD_INFO: (params: { guild: Guild }) => string;
		COMMAND_REMOVE_DESCRIPTION: string;
		COMMAND_REMOVE_INDEX_INVALID: string;
		COMMAND_REMOVE_INDEX_OUT: (params: { amount: number }) => string;
		COMMAND_REMOVE_DENIED: string;
		COMMAND_REMOVE_SUCCESS: (params: { song: Song }) => string;
		COMMAND_SEEK_DESCRIPTION: string;
		COMMAND_SEEK_SUCCESS: (params: { time: number }) => string;
		COMMAND_RESUME_DESCRIPTION: string;
		COMMAND_RESUME_SUCCESS: string;
		COMMAND_ROLESET_DESCRIPTION: string;
		COMMAND_ROLESET_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ROLESET_CREATED: (params: { name: string; roles: readonly string[] }) => string;
		COMMAND_ROLESET_ADDED: (params: { name: string; roles: readonly string[] }) => string;
		COMMAND_ROLESET_INVALID_NAME: (params: { name: string }) => string;
		COMMAND_ROLESET_REMOVED: (params: { name: string; roles: readonly string[] }) => string;
		COMMAND_ROLESET_RESET_EMPTY: string;
		COMMAND_ROLESET_RESET_ALL: string;
		COMMAND_ROLESET_RESET_NOT_EXISTS: (params: { name: string }) => string;
		COMMAND_ROLESET_RESET_GROUP: (params: { name: string }) => string;
		COMMAND_ROLESET_UPDATED: (params: { name: string }) => string;
		COMMAND_SHUFFLE_DESCRIPTION: string;
		COMMAND_SHUFFLE_SUCCESS: (params: { amount: number }) => string;
		COMMAND_SKIP_DESCRIPTION: string;
		COMMAND_SKIP_PERMISSIONS: string;
		COMMAND_SKIP_VOTES_VOTED: string;
		COMMAND_SKIP_VOTES_TOTAL: (params: { amount: number; needed: number }) => string;
		COMMAND_SKIP_SUCCESS: (params: { title: string }) => string;
		COMMAND_SUPPORT_EMBED_TITLE: (params: { username: string }) => string;
		COMMAND_SUPPORT_EMBED_DESCRIPTION: string;
		COMMAND_PLAYING_TIME_DESCRIPTION: string;
		COMMAND_PLAYING_TIME_QUEUE_EMPTY: string;
		COMMAND_PROMOTE_DESCRIPTION: string;
		COMMAND_PROMOTE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PROMOTE_SUCCESS: (params: { song: Song }) => string;
		COMMAND_VOLUME_DESCRIPTION: string;
		COMMAND_VOLUME_SUCCESS: (params: { volume: number }) => string;
		COMMAND_VOLUME_CHANGED: (params: { emoji: string; volume: number }) => string;
		COMMAND_VOLUME_CHANGED_EXTREME: (params: { emoji: string; text: string; volume: number }) => string;
		COMMAND_VOLUME_CHANGED_TEXTS: () => string;
		COMMAND_ABILITY_DESCRIPTION: string;
		COMMAND_ABILITY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ABILITY_EMBED_DATA: {
			ABILITY: string;
			EXTERNAL_RESOURCES: string;
		};
		COMMAND_ABILITY_QUERY_FAIL: (params: { ability: string }) => string;
		COMMAND_FLAVORS_DESCRIPTION: string;
		COMMAND_FLAVORS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FLAVORS_QUERY_FAIL: (params: { pokemon: string }) => string;
		COMMAND_ITEM_DESCRIPTION: string;
		COMMAND_ITEM_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ITEM_EMEBED_DATA: {
			ITEM: string;
			GENERATION_INTRODUCED: string;
			AVAILABLE_IN_GENERATION_8_TITLE: string;
			AVAILABLE_IN_GENERATION_8_DATA: (params: { available: boolean }) => string;
			EXTERNAL_RESOURCES: string;
		};
		COMMAND_ITEM_QUERY_FAIL: (params: { item: string }) => string;
		COMMAND_LEARN_DESCRIPTION: string;
		COMMAND_LEARN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LEARN_METHOD_TYPES: {
			levelUpMoves: (params: { level: number }) => string;
			eventMoves: (params: { level: number }) => string;
			tutorMoves: (params: { level: number }) => string;
			eggMoves: (params: { level: number }) => string;
			virtualTransferMoves: (params: { level: number }) => string;
			tmMoves: (params: { level: number }) => string;
			dreamworldMoves: (params: { level: number }) => string;
		};
		COMMAND_LEARN_INVALID_GENERATION: (params: { generation: string }) => string;
		COMMAND_LEARN_METHOD: (params: { generation: number; pokemon: string; move: string; method: string }) => string;
		COMMAND_LEARN_QUERY_FAILED: (params: { pokemon: string; moves: string[] }) => string;
		COMMAND_LEARN_CANNOT_LEARN: (params: { pokemon: string; moves: string[] }) => string;
		COMMAND_LEARN_TITLE: (params: { pokemon: string; generation: number }) => string;
		COMMAND_MOVE_DESCRIPTION: string;
		COMMAND_MOVE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MOVE_EMBED_DATA: {
			MOVE: string;
			TYPE: string;
			BASE_POWER: string;
			PP: string;
			CATEGORY: string;
			ACCURACY: string;
			PRIORITY: string;
			TARGET: string;
			CONTEST_CONDITION: string;
			Z_CRYSTAL: string;
			GMAX_POKEMON: string;
			AVAILABLE_IN_GENERATION_8_TITLE: string;
			AVAILABLE_IN_GENERATION_8_DATA: (params: { available: boolean }) => string;
			EXTERNAL_RESOURCES: string;
			NONE: string;
			MAX_MOVE_POWER: string;
			Z_MOVE_POWER: string;
		};
		COMMAND_MOVE_QUERY_FAIL: (params: { move: string }) => string;
		COMMAND_POKEDEX_DESCRIPTION: string;
		COMMAND_POKEDEX_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_POKEDEX_EMBED_DATA: {
			TYPES: string;
			ABILITIES: string;
			GENDER_RATIO: string;
			SMOGON_TIER: string;
			UKNOWN_SMOGON_TIER: string;
			HEIGHT: string;
			WEIGHT: string;
			EGG_GROUPS: string;
			EVOLUTIONARY_LINE: string;
			BASE_STATS: string;
			BASE_STATS_TOTAL: string;
			FLAVOUR_TEXT: string;
			EXTERNAL_RESOURCES: string;
			OTHER_FORMES_TITLE: string;
			COSMETIC_FORMES_TITLE: string;
			FORMES_LIST: (params: { formes: readonly string[] }) => string;
		};
		COMMAND_POKEDEX_QUERY_FAIL: (params: { pokemon: string }) => string;
		COMMAND_TYPE_DESCRIPTION: string;
		COMMAND_TYPE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TYPE_EMBED_DATA: {
			OFFENSIVE: string;
			DEFENSIVE: string;
			SUPER_EFFECTIVE_AGAINST: string;
			DEALS_NORMAL_DAMAGE_TO: string;
			DOES_NOT_AFFECT: string;
			NOT_VERY_EFFECTIVE_AGAINST: string;
			VULNERABLE_TO: string;
			TAKES_NORMAL_DAMAGE_FROM: string;
			RESISTS: string;
			NOT_AFFECTED_BY: string;
			EXTERNAL_RESOURCES: string;
			TYPE_EFFECTIVENESS_FOR: (params: { type: string[] }) => string;
		};
		COMMAND_TYPE_TOO_MANY_TYPES: string;
		COMMAND_TYPE_NOT_A_TYPE: (params: { type: string }) => string;
		COMMAND_TYPE_QUERY_FAIL: (params: { types: string[] }) => string;
		INHIBITOR_MUSIC_QUEUE_EMPTY: string;
		INHIBITOR_MUSIC_NOT_PLAYING: string;
		INHIBITOR_MUSIC_PAUSED: string;
		INHIBITOR_MUSIC_DJ_MEMBER: string;
		INHIBITOR_MUSIC_USER_VOICE_CHANNEL: string;
		INHIBITOR_MUSIC_BOT_VOICE_CHANNEL: string;
		INHIBITOR_MUSIC_BOTH_VOICE_CHANNEL: string;
		INHIBITOR_MUSIC_NOTHING_PLAYING: string;
		MUSICMANAGER_FETCH_NO_ARGUMENTS: string;
		MUSICMANAGER_FETCH_NO_MATCHES: string;
		MUSICMANAGER_FETCH_LOAD_FAILED: string;
		MUSICMANAGER_TOO_MANY_SONGS: string;
		MUSICMANAGER_SETVOLUME_SILENT: string;
		MUSICMANAGER_SETVOLUME_LOUD: string;
		MUSICMANAGER_PLAY_NO_SONGS: string;
		MUSICMANAGER_PLAY_PLAYING: string;
		MUSICMANAGER_STUCK: (params: { milliseconds: number }) => string;
		COMMAND_CONF_MENU_NOPERMISSIONS: string;
		COMMAND_CONF_MENU_RENDER_AT_FOLDER: (params: { path: string }) => string;
		COMMAND_CONF_MENU_RENDER_AT_PIECE: (params: { path: string }) => string;
		COMMAND_CONF_MENU_RENDER_NOKEYS: string;
		COMMAND_CONF_MENU_RENDER_SELECT: string;
		COMMAND_CONF_MENU_RENDER_TCTITLE: string;
		COMMAND_CONF_MENU_RENDER_UPDATE: string;
		COMMAND_CONF_MENU_RENDER_REMOVE: string;
		COMMAND_CONF_MENU_RENDER_RESET: string;
		COMMAND_CONF_MENU_RENDER_UNDO: string;
		COMMAND_CONF_MENU_RENDER_CVALUE: (params: { value: string }) => string;
		COMMAND_CONF_MENU_RENDER_BACK: string;
		COMMAND_CONF_MENU_INVALID_KEY: string;
		COMMAND_CONF_MENU_INVALID_ACTION: string;
		COMMAND_CONF_MENU_SAVED: string;
		SETTINGS_PREFIX: string;
		SETTINGS_LANGUAGE: string;
		SETTINGS_DISABLEDCOMMANDS: string;
		SETTINGS_DISABLENATURALPREFIX: string;
		SETTINGS_CHANNELS_ANNOUNCEMENTS: string;
		SETTINGS_CHANNELS_FAREWELL: string;
		SETTINGS_CHANNELS_GREETING: string;
		SETTINGS_CHANNELS_IMAGE_LOGS: string;
		SETTINGS_CHANNELS_MEMBER_LOGS: string;
		SETTINGS_CHANNELS_MESSAGE_LOGS: string;
		SETTINGS_CHANNELS_MODERATION_LOGS: string;
		SETTINGS_CHANNELS_NSFW_MESSAGE_LOGS: string;
		SETTINGS_CHANNELS_PRUNE_LOGS: string;
		SETTINGS_CHANNELS_REACTION_LOGS: string;
		SETTINGS_CHANNELS_ROLES: string;
		SETTINGS_CHANNELS_SPAM: string;
		SETTINGS_DISABLEDCHANNELS: string;
		SETTINGS_EVENTS_BANADD: string;
		SETTINGS_EVENTS_BANREMOVE: string;
		SETTINGS_EVENTS_MEMBERADD: string;
		SETTINGS_EVENTS_MEMBERNAMEUPDATE: string;
		SETTINGS_EVENTS_MEMBERREMOVE: string;
		SETTINGS_EVENTS_MESSAGEDELETE: string;
		SETTINGS_EVENTS_MESSAGEEDIT: string;
		SETTINGS_EVENTS_TWEMOJI_REACTIONS: string;
		SETTINGS_MESSAGES_FAREWELL: string;
		SETTINGS_MESSAGES_GREETING: string;
		SETTINGS_MESSAGES_IGNORECHANNELS: string;
		SETTINGS_MESSAGES_JOIN_DM: string;
		SETTINGS_MESSAGES_MODERATION_AUTO_DELETE: string;
		SETTINGS_MESSAGES_MODERATION_DM: string;
		SETTINGS_MESSAGES_MODERATION_MESSAGE_DISPLAY: string;
		SETTINGS_MESSAGES_MODERATION_REASON_DISPLAY: string;
		SETTINGS_MESSAGES_MODERATOR_NAME_DISPLAY: string;
		SETTINGS_MESSAGES_WARNINGS: string;
		SETTINGS_MUSIC_ALLOW_STREAMS: string;
		SETTINGS_MUSIC_DEFAULT_VOLUME: string;
		SETTINGS_MUSIC_MAXIMUM_DURATION: string;
		SETTINGS_MUSIC_MAXIMUM_ENTRIES_PER_USER: string;
		SETTINGS_NO_MENTION_SPAM_ALERTS: string;
		SETTINGS_NO_MENTION_SPAM_ENABLED: string;
		SETTINGS_NO_MENTION_SPAM_MENTIONSALLOWED: string;
		SETTINGS_NO_MENTION_SPAM_TIMEPERIOD: string;
		SETTINGS_ROLES_ADMIN: string;
		SETTINGS_ROLES_DJ: string;
		SETTINGS_ROLES_INITIAL: string;
		SETTINGS_ROLES_MODERATOR: string;
		SETTINGS_ROLES_MUTED: string;
		SETTINGS_ROLES_PUBLIC: string;
		SETTINGS_ROLES_REMOVEINITIAL: string;
		SETTINGS_ROLES_RESTRICTED_ATTACHMENT: string;
		SETTINGS_ROLES_RESTRICTED_EMBED: string;
		SETTINGS_ROLES_RESTRICTED_EMOJI: string;
		SETTINGS_ROLES_RESTRICTED_REACTION: string;
		SETTINGS_ROLES_RESTRICTED_VOICE: string;
		SETTINGS_ROLES_SUBSCRIBER: string;
		SETTINGS_SELFMOD_ATTACHMENT: string;
		SETTINGS_SELFMOD_ATTACHMENTMAXIMUM: string;
		SETTINGS_SELFMOD_CAPITALS_ENABLED: string;
		SETTINGS_SELFMOD_CAPITALS_IGNOREDCHANNELS: string;
		SETTINGS_SELFMOD_CAPITALS_IGNOREDROLES: string;
		SETTINGS_SELFMOD_CAPITALS_MAXIMUM: string;
		SETTINGS_SELFMOD_CAPITALS_MINIMUM: string;
		SETTINGS_SELFMOD_FILTER_ENABLED: string;
		SETTINGS_SELFMOD_FILTER_IGNOREDCHANNELS: string;
		SETTINGS_SELFMOD_FILTER_IGNOREDROLES: string;
		SETTINGS_SELFMOD_IGNORECHANNELS: string;
		SETTINGS_SELFMOD_INVITES_ENABLED: string;
		SETTINGS_SELFMOD_INVITES_IGNOREDCHANNELS: string;
		SETTINGS_SELFMOD_INVITES_IGNOREDROLES: string;
		SETTINGS_SELFMOD_LINKS_ENABLED: string;
		SETTINGS_SELFMOD_LINKS_IGNOREDCHANNELS: string;
		SETTINGS_SELFMOD_LINKS_IGNOREDROLES: string;
		SETTINGS_SELFMOD_LINKS_WHITELIST: string;
		SETTINGS_SELFMOD_MESSAGES_ENABLED: string;
		SETTINGS_SELFMOD_MESSAGES_IGNOREDCHANNELS: string;
		SETTINGS_SELFMOD_MESSAGES_IGNOREDROLES: string;
		SETTINGS_SELFMOD_MESSAGES_MAXIMUM: string;
		SETTINGS_SELFMOD_MESSAGES_QUEUE_SIZE: string;
		SETTINGS_SELFMOD_NEWLINES_ENABLED: string;
		SETTINGS_SELFMOD_NEWLINES_IGNOREDCHANNELS: string;
		SETTINGS_SELFMOD_NEWLINES_IGNOREDROLES: string;
		SETTINGS_SELFMOD_NEWLINES_MAXIMUM: string;
		SETTINGS_SELFMOD_RAID: string;
		SETTINGS_SELFMOD_RAIDTHRESHOLD: string;
		SETTINGS_SELFMOD_REACTIONS_BLACKLIST: string;
		SETTINGS_SELFMOD_REACTIONS_ENABLED: string;
		SETTINGS_SELFMOD_REACTIONS_IGNOREDCHANNELS: string;
		SETTINGS_SELFMOD_REACTIONS_IGNOREDROLES: string;
		SETTINGS_SELFMOD_REACTIONS_WHITELIST: string;
		SETTINGS_SOCIAL_ACHIEVE: string;
		SETTINGS_SOCIAL_ACHIEVEMESSAGE: string;
		SETTINGS_SOCIAL_IGNORECHANNELS: string;
		SETTINGS_STARBOARD_CHANNEL: string;
		SETTINGS_STARBOARD_IGNORECHANNELS: string;
		SETTINGS_STARBOARD_MINIMUM: string;
		SETTINGS_SUGGESTIONS_CHANNEL: string;
		SETTINGS_SUGGESTIONS_EMOJIS_UPVOTE: string;
		SETTINGS_SUGGESTIONS_EMOJIS_DOWNVOTE: string;
		SETTINGS_SUGGESTIONS_ON_ACTION_DM: string;
		SETTINGS_SUGGESTIONS_ON_ACTION_REPOST: string;
		SETTINGS_SUGGESTIONS_ON_ACTION_HIDE_AUTHOR: string;
		COMMAND_CATFACT_DESCRIPTION: string;
		COMMAND_CATFACT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DOG_DESCRIPTION: string;
		COMMAND_DOG_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FOX_DESCRIPTION: string;
		COMMAND_FOX_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_KITTY_DESCRIPTION: string;
		COMMAND_KITTY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SHIBE_DESCRIPTION: string;
		COMMAND_SHIBE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ANIME_DESCRIPTION: string;
		COMMAND_ANIME_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MANGA_DESCRIPTION: string;
		COMMAND_MANGA_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WAIFU_DESCRIPTION: string;
		COMMAND_WAIFU_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ANNOUNCEMENT_DESCRIPTION: string;
		COMMAND_ANNOUNCEMENT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SUBSCRIBE_DESCRIPTION: string;
		COMMAND_SUBSCRIBE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNSUBSCRIBE_DESCRIPTION: string;
		COMMAND_UNSUBSCRIBE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CHOICE_DESCRIPTION: string;
		COMMAND_CHOICE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CHANGEMYMIND_DESCRIPTION: string;
		COMMAND_CHANGEMYMIND_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DICE_DESCRIPTION: string;
		COMMAND_DICE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ESCAPEROPE_DESCRIPTION: string;
		COMMAND_ESCAPEROPE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_HOWTOFLIRT_DESCRIPTION: string;
		COMMAND_HOWTOFLIRT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LOVE_DESCRIPTION: string;
		COMMAND_LOVE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MARKOV_TIMER: (params: { timer: string }) => string;
		COMMAND_MARKOV_NO_MESSAGES: string;
		COMMAND_MARKOV_DESCRIPTION: string;
		COMMAND_MARKOV_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_NORRIS_DESCRIPTION: string;
		COMMAND_NORRIS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RATE_DESCRIPTION: string;
		COMMAND_RATE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_XKCD_DESCRIPTION: string;
		COMMAND_XKCD_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PUN_DESCRIPTION: string;
		COMMAND_PUN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WAKANDA_DESCRIPTION: string;
		COMMAND_WAKANDA_EXTENDED: LanguageHelpDisplayOptions;
		// GI commands
		COMMAND_BRAWLSTARS_DESCRIPTION: string;
		COMMAND_BRAWLSTARS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_BRAWLSTARS_PLAYER_EMBED_TITLES: {
			TROPHIES: string;
			EXP: string;
			EVENTS: string;
			GAME_MODES: string;
			OTHER: string;
		};
		COMMAND_BRAWLSTARS_PLAYER_EMBED_FIELDS: {
			TOTAL: string;
			PERSONAL_BEST: string;
			EXPERIENCE_LEVEL: string;
			EVENTS: string;
			ROBO_RUMBLE: string;
			BOSS_FIGHT: string;
			VICTORIES_3V3: string;
			VICTORIES_DUO: string;
			VICTORIES_SOLO: string;
			CLUB: string;
			BRAWLERS_UNLOCKED: string;
		};
		COMMAND_BRAWLSTARS_CLUB_EMBED_TITLES: {
			TOTAL_TROPHIES: string;
			AVERAGE_TROPHIES: string;
			REQUIRED_TROPHIES: string;
			MEMBERS: string;
			TYPE: string;
			TOP_5_MEMBERS: string;
			PRESIDENT: string;
		};
		COMMAND_BRAWLSTARS_CLUB_EMBED_FIELDS: {
			NO_PRESIDENT: string;
		};
		COMMAND_CLASHOFCLANS_DESCRIPTION: string;
		COMMAND_CLASHOFCLANS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CLASHOFCLANS_PLAYER_EMBED_TITLES: {
			XP_LEVEL: string;
			BUILDER_HALL_LEVEL: string;
			TOWNHALL_LEVEL: string;
			TOWNHALL_WEAPON_LEVEL: string;
			TROPHIES: string;
			BEST_TROPHIES: string;
			WAR_STARS: string;
			ATTACK_WINS: string;
			DEFENSE_WINS: string;
			AMOUNT_OF_ACHIEVEMENTS: string;
			VERSUS_TROPHIES: string;
			BEST_VERSUS_TROPHIES: string;
			VERSUS_BATTLE_WINS: string;
			CLAN_ROLE: string;
			CLAN_NAME: string;
			LEAGUE_NAME: string;
			NO_TOWNHALL_WEAPON_LEVEL: string;
			NO_ROLE: string;
			NO_CLAN: string;
			NO_LEAGUE: string;
		};
		COMMAND_CLASHOFCLANS_CLAN_EMBED_TITLES: {
			CLAN_LEVEL: string;
			CLAN_POINTS: string;
			CLAN_VERSUS_POINTS: string;
			AMOUNT_OF_MEMBERS: string;
			DESCRIPTION: string;
			LOCATION_NAME: string;
			WAR_FREQUENCY: string;
			WAR_WIN_STREAK: string;
			WAR_WINS: string;
			WAR_TIES: string;
			WAR_LOSSES: string;
			WAR_LOG_PUBLIC: string;
			UNKNOWN: string;
			WAR_FREQUENCY_DESCR: {
				moreThanOncePerWeek: string;
				unknown: string;
				always: string;
				oncePerWeek: string;
				lessThanOncePerWeek: string;
			};
			WAR_LOG_PUBLIC_DESCR: (params: { isWarLogPublic: boolean }) => string;
		};
		COMMAND_CLASHOFCLANS_INVALID_PLAYER_TAG: (params: { playertag: string }) => string;
		COMMAND_CLASHOFCLANS_CLANS_QUERY_FAIL: (params: { clan: string }) => string;
		COMMAND_CLASHOFCLANS_PLAYERS_QUERY_FAIL: (params: { playertag: string }) => string;
		COMMAND_FFXIV_DESCRIPTION: string;
		COMMAND_FFXIV_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FFXIV_CHARACTER_FIELDS: {
			SERVER_AND_DC: string;
			TRIBE: string;
			CHARACTER_GENDER: string;
			NAMEDAY: string;
			GUARDIAN: string;
			CITY_STATE: string;
			GRAND_COMPANY: string;
			RANK: string;
			NONE: string;
			MALE: string;
			FEMALE: string;
			DOW_DOM_CLASSES: string;
			TANK: string;
			HEALER: string;
			MELEEDPS: string;
			PHYSICALRANGEDDPS: string;
			MAGICALRANGEDDPS: string;
			DOH_CLASSES: string;
			DOL_CLASSES: string;
		};
		COMMAND_FFXIV_ITEM_FIELDS: {
			KIND: string;
			CATEGORY: string;
			LEVEL_EQUIP: string;
			NONE: string;
		};
		COMMAND_FFXIV_NO_CHARACTER_FOUND: string;
		COMMAND_FFXIV_INVALID_SERVER: string;
		COMMAND_FFXIV_NO_ITEM_FOUND: string;
		COMMAND_FORTNITE_DESCRIPTION: string;
		COMMAND_FORTNITE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FORTNITE_NO_USER: string;
		COMMAND_FORTNITE_TITLES: {
			TITLE: (params: { epicUserHandle: string }) => string;
			LIFETIME_STATS: string;
			SOLOS: string;
			DUOS: string;
			SQUADS: string;
			WINS: (params: { count: string }) => string;
			KILLS: (params: { count: string }) => string;
			KDR: (params: { count: string }) => string;
			MATCHES_PLAYED: (params: { count: string }) => string;
			TOP_1S: (params: { count: string }) => string;
			TOP_3S: (params: { count: string }) => string;
			TOP_5S: (params: { count: string }) => string;
			TOP_6S: (params: { count: string }) => string;
			TOP_10S: (params: { count: string }) => string;
			TOP_12S: (params: { count: string }) => string;
			TOP_25S: (params: { count: string }) => string;
		};
		COMMAND_OVERWATCH_DESCRIPTION: string;
		COMMAND_OVERWATCH_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_OVERWATCH_INVALID_PLAYER_NAME: (params: { playerTag: string }) => string;
		COMMAND_OVERWATCH_QUERY_FAIL: (params: { player: string; platform: string }) => string;
		COMMAND_OVERWATCH_NO_STATS: (params: { player: string }) => string;
		COMMMAND_OVERWATCH_EMBED_DATA: {
			TITLE: string;
			RATINGS_TITLE: string;
			NO_AVERAGE: string;
			AUTHOR: (params: { name: string }) => string;
			PLAYER_LEVEL: (params: { level: number }) => string;
			PRESTIGE_LEVEL: (params: { level: number }) => string;
			RATINGS: (params: { ratings: Array<{ role: OverwatchRating['role'] | 'average'; level: OverwatchRating['level'] | string }> }) => string;
			TOTAL_GAMES_WON: (params: { gamesWon: number }) => string;
			FINAL_BLOWS: (params: { finalBlows: number }) => string;
			DEATHS: (params: { deaths: number }) => string;
			DAMAGE_DEALT: (params: { damageDone: number }) => string;
			HEALING: (params: { healingDone: number }) => string;
			OBJECTIVE_KILLS: (params: { objectiveKills: number }) => string;
			SOLO_KILLS: (params: { soloKills: number }) => string;
			PLAY_TIME: (params: { timePlayed: number }) => string;
			GAMES_WON: (params: { gamesWon: number }) => string;
			GOLDEN_MEDALS: (params: { medalsGold: number }) => string;
			SILVER_MEDALS: (params: { medalsSilver: number }) => string;
			BRONZE_MEDALS: (params: { medalsBronze: number }) => string;
			TOP_HERO: (params: { heroName: string; timePlayed: string }) => string;
			HEADERS: {
				ACCOUNT: string;
				QUICKPLAY: string;
				COMPETITIVE: string;
				TOP_HEROES_QUICKPLAY: string;
				TOP_HEROES_COMPETITIVE: string;
			};
		};
		GAMES_NOT_ENOUGH_MONEY: (params: { money: number }) => string;
		GAMES_CANNOT_HAVE_NEGATIVE_MONEY: string;
		COMMAND_CREATEMUTE_DESCRIPTION: string;
		COMMAND_CREATEMUTE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GIVEAWAY_DESCRIPTION: string;
		COMMAND_GIVEAWAY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GIVEAWAYREROLL_DESCRIPTION: string;
		COMMAND_GIVEAWAYREROLL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GIVEAWAYSCHEDULE_DESCRIPTION: string;
		COMMAND_GIVEAWAYSCHEDULE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CURRENTTIME_DESCRIPTION: string;
		COMMAND_CURRENTTIME_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CURRENTTIME_LOCATION_NOT_FOUND: string;
		COMMAND_CURRENTTIME_TITLES: {
			CURRENT_TIME: string;
			CURRENT_DATE: string;
			COUNTRY: string;
			GMT_OFFSET: string;
			DST: (params: { dst: number }) => string;
		};
		COMMAND_GSEARCH_DESCRIPTION: string;
		COMMAND_GSEARCH_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GIMAGE_DESCRIPTION: string;
		COMMAND_GIMAGE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LMGTFY_DESCRIPTION: string;
		COMMAND_LMGTFY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LMGTFY_CLICK: string;
		COMMAND_WEATHER_DESCRIPTION: string;
		COMMAND_WEATHER_EXTENDED: LanguageHelpDisplayOptions;
		GOOGLE_ERROR_ZERO_RESULTS: string;
		GOOGLE_ERROR_REQUEST_DENIED: string;
		GOOGLE_ERROR_INVALID_REQUEST: string;
		GOOGLE_ERROR_OVER_QUERY_LIMIT: string;
		GOOGLE_ERROR_UNKNOWN: string;
		COMMAND_NICK_DESCRIPTION: string;
		COMMAND_NICK_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PERMISSIONNODES_DESCRIPTION: string;
		COMMAND_PERMISSIONNODES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TRIGGERS_DESCRIPTION: string;
		COMMAND_TRIGGERS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MANAGECOMMANDAUTODELETE_DESCRIPTION: string;
		COMMAND_MANAGECOMMANDAUTODELETE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MANAGECOMMANDCHANNEL_DESCRIPTION: string;
		COMMAND_MANAGECOMMANDCHANNEL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MANAGEREACTIONROLES_DESCRIPTION: string;
		COMMAND_MANAGEREACTIONROLES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETIGNORECHANNELS_DESCRIPTION: string;
		COMMAND_SETIGNORECHANNELS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETIMAGELOGS_DESCRIPTION: string;
		COMMAND_SETIMAGELOGS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETMEMBERLOGS_DESCRIPTION: string;
		COMMAND_SETMEMBERLOGS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETMESSAGELOGS_DESCRIPTION: string;
		COMMAND_SETMESSAGELOGS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETMODLOGS_DESCRIPTION: string;
		COMMAND_SETMODLOGS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETPREFIX_DESCRIPTION: string;
		COMMAND_SETPREFIX_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETROLECHANNEL_DESCRIPTION: string;
		COMMAND_SETROLECHANNEL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETROLEMESSAGE_DESCRIPTION: string;
		COMMAND_SETROLEMESSAGE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETSTARBOARDEMOJI_DESCRIPTION: string;
		COMMAND_SETSTARBOARDEMOJI_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GIVEAWAYREROLL_INVALID: string;
		COMMAND_ROLEINFO_DESCRIPTION: string;
		COMMAND_ROLEINFO_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GUILDINFO_DESCRIPTION: string;
		COMMAND_GUILDINFO_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_STICKYROLES_DESCRIPTION: string;
		COMMAND_STICKYROLES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MANAGEATTACHMENTS_DESCRIPTION: string;
		COMMAND_MANAGEATTACHMENTS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CAPITALSMODE_DESCRIPTION: string;
		COMMAND_CAPITALSMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FILTER_DESCRIPTION: string;
		COMMAND_FILTER_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FILTERMODE_DESCRIPTION: string;
		COMMAND_FILTERMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_INVITEMODE_DESCRIPTION: string;
		COMMAND_INVITEMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LINKMODE_DESCRIPTION: string;
		COMMAND_LINKMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MESSAGEMODE_DESCRIPTION: string;
		COMMAND_MESSAGEMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_NEWLINEMODE_DESCRIPTION: string;
		COMMAND_NEWLINEMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_REACTIONMODE_DESCRIPTION: string;
		COMMAND_REACTIONMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CUDDLE_DESCRIPTION: string;
		COMMAND_CUDDLE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DELETTHIS_DESCRIPTION: string;
		COMMAND_DELETTHIS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_F_DESCRIPTION: string;
		COMMAND_F_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GOODNIGHT_DESCRIPTION: string;
		COMMAND_GOODNIGHT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_GOOFYTIME_DESCRIPTION: string;
		COMMAND_GOOFYTIME_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_HUG_DESCRIPTION: string;
		COMMAND_HUG_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_INEEDHEALING_DESCRIPTION: string;
		COMMAND_INEEDHEALING_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RANDREDDIT_DESCRIPTION: string;
		COMMAND_RANDREDDIT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CHASE_DESCRIPTION: string;
		COMMAND_CHASE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SHINDEIRU_DESCRIPTION: string;
		COMMAND_SHINDEIRU_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PEEPOLOVE_DESCRIPTION: string;
		COMMAND_PEEPOLOVE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SLAP_DESCRIPTION: string;
		COMMAND_SLAP_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SNIPE_DESCRIPTION: string;
		COMMAND_SNIPE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_THESEARCH_DESCRIPTION: string;
		COMMAND_THESEARCH_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TRIGGERED_DESCRIPTION: string;
		COMMAND_TRIGGERED_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UPVOTE_DESCRIPTION: string;
		COMMAND_UPVOTE_EXTENDED: LanguageHelpDisplayOptions;

		COMMAND_SETNICKNAME_DESCRIPTION: string;
		COMMAND_SETNICKNAME_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ADDROLE_DESCRIPTION: string;
		COMMAND_ADDROLE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_REMOVEROLE_DESCRIPTION: string;
		COMMAND_REMOVEROLE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ARCHIVE_DESCRIPTION: string;
		COMMAND_ARCHIVE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CASE_DESCRIPTION: string;
		COMMAND_CASE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SLOWMODE_DESCRIPTION: string;
		COMMAND_SLOWMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_BAN_DESCRIPTION: string;
		COMMAND_BAN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DEHOIST_DESCRIPTION: string;
		COMMAND_DEHOIST_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_KICK_DESCRIPTION: string;
		COMMAND_KICK_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LOCKDOWN_DESCRIPTION: string;
		COMMAND_LOCKDOWN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MUTE_DESCRIPTION: string;
		COMMAND_MUTE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PRUNE_DESCRIPTION: string;
		COMMAND_PRUNE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_REASON_DESCRIPTION: string;
		COMMAND_REASON_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RESTRICTATTACHMENT_DESCRIPTION: string;
		COMMAND_RESTRICTATTACHMENT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RESTRICTEMBED_DESCRIPTION: string;
		COMMAND_RESTRICTEMBED_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RESTRICTEMOJI_DESCRIPTION: string;
		COMMAND_RESTRICTEMOJI_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RESTRICTREACTION_DESCRIPTION: string;
		COMMAND_RESTRICTREACTION_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RESTRICTVOICE_DESCRIPTION: string;
		COMMAND_RESTRICTVOICE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SOFTBAN_DESCRIPTION: string;
		COMMAND_SOFTBAN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TOGGLEMODERATIONDM_DESCRIPTION: string;
		COMMAND_TOGGLEMODERATIONDM_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNBAN_DESCRIPTION: string;
		COMMAND_UNBAN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNMUTE_DESCRIPTION: string;
		COMMAND_UNMUTE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNRESTRICTATTACHMENT_DESCRIPTION: string;
		COMMAND_UNRESTRICTATTACHMENT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNRESTRICTEMBED_DESCRIPTION: string;
		COMMAND_UNRESTRICTEMBED_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNRESTRICTEMOJI_DESCRIPTION: string;
		COMMAND_UNRESTRICTEMOJI_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNRESTRICTREACTION_DESCRIPTION: string;
		COMMAND_UNRESTRICTREACTION_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNRESTRICTVOICE_DESCRIPTION: string;
		COMMAND_UNRESTRICTVOICE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_UNWARN_DESCRIPTION: string;
		COMMAND_UNWARN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_VMUTE_DESCRIPTION: string;
		COMMAND_VMUTE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_VOICEKICK_DESCRIPTION: string;
		COMMAND_VOICEKICK_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_VUNMUTE_DESCRIPTION: string;
		COMMAND_VUNMUTE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WARN_DESCRIPTION: string;
		COMMAND_WARN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SOCIAL_DESCRIPTION: string;
		COMMAND_SOCIAL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_BANNER_DESCRIPTION: string;
		COMMAND_BANNER_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TOGGLEDARKMODE_DESCRIPTION: string;
		COMMAND_TOGGLEDARKMODE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_AUTOROLE_DESCRIPTION: string;
		COMMAND_AUTOROLE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_BALANCE_DESCRIPTION: string;
		COMMAND_BALANCE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DAILY_DESCRIPTION: string;
		COMMAND_DAILY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LEADERBOARD_DESCRIPTION: string;
		COMMAND_LEADERBOARD_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_LEVEL_DESCRIPTION: string;
		COMMAND_LEVEL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DIVORCE_DESCRIPTION: string;
		COMMAND_DIVORCE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MARRY_DESCRIPTION: string;
		COMMAND_MARRY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MYLEVEL_DESCRIPTION: string;
		COMMAND_MYLEVEL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PAY_DESCRIPTION: string;
		COMMAND_PAY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_PROFILE_DESCRIPTION: string;
		COMMAND_PROFILE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_REMINDME_DESCRIPTION: string;
		COMMAND_REMINDME_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_REPUTATION_DESCRIPTION: string;
		COMMAND_REPUTATION_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETCOLOR_DESCRIPTION: string;
		COMMAND_SETCOLOR_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_STAR_DESCRIPTION: string;
		COMMAND_STAR_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SUGGEST_DESCRIPTION: string;
		COMMAND_SUGGEST_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_RESOLVESUGGESTION_DESCRIPTION: string;
		COMMAND_RESOLVESUGGESTION_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DM_DESCRIPTION: string;
		COMMAND_DM_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_EVAL_DESCRIPTION: string;
		COMMAND_EVAL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_EXEC_DESCRIPTION: string;
		COMMAND_EXEC_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SETAVATAR_DESCRIPTION: string;
		COMMAND_SETAVATAR_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DONATE_DESCRIPTION: string;
		COMMAND_DONATE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ECHO_DESCRIPTION: string;
		COMMAND_ECHO_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FEEDBACK_DESCRIPTION: string;
		COMMAND_FEEDBACK_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_STATS_DESCRIPTION: string;
		COMMAND_STATS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_AVATAR_DESCRIPTION: string;
		COMMAND_AVATAR_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_COLOR_DESCRIPTION: string;
		COMMAND_COLOR_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_CONTENT_DESCRIPTION: string;
		COMMAND_CONTENT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_EMOJI_DESCRIPTION: string;
		COMMAND_EMOJI_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_COUNTRY_DESCRIPTION: string;
		COMMAND_COUNTRY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_COUNTRY_TITLES: {
			OVERVIEW: string;
			LANGUAGES: string;
			OTHER: string;
		};
		COMMAND_COUNTRY_FIELDS: {
			OVERVIEW: {
				OFFICIAL_NAME: string;
				CAPITAL: string;
				POPULATION: string;
			};
			OTHER: {
				DEMONYM: string;
				AREA: string;
				CURRENCIES: string;
			};
		};
		COMMAND_ESHOP_DESCRIPTION: string;
		COMMAND_ESHOP_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ESHOP_NOT_IN_DATABASE: string;
		COMMAND_ESHOP_TITLES: {
			PRICE: string;
			AVAILABILITY: string;
			RELEASE_DATE: string;
			NUMBER_OF_PLAYERS: string;
			PLATFORM: string;
			CATEGORIES: string;
			NO_CATEGORIES: string;
			NSUID: 'NSUID';
			ESRB: 'ESRB';
		};
		COMMAND_ESHOP_PRICE: (params: { price: number }) => string;
		COMMAND_HOROSCOPE_DESCRIPTION: string;
		COMMAND_HOROSCOPE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_HOROSCOPE_INVALID_SUNSIGN: (params: { sign: string; maybe: string }) => string;
		COMMAND_HOROSCOPE_TITLES: {
			DAILY_HOROSCOPE: (params: { sign: string }) => string;
			METADATA_TITLE: string;
			METADATA: (params: { intensity: string; keywords: readonly string[]; mood: string; rating: string }) => string;
		};
		COMMAND_IGDB_DESCRIPTION: string;
		COMMAND_IGDB_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_IGDB_TITLES: {
			USER_SCORE: string;
			AGE_RATING: string;
			RELEASE_DATE: string;
			GENRES: string;
			DEVELOPERS: string;
			PLATFORMS: string;
		};
		COMMAND_IGDB_DATA: {
			NO_DEVELOPERS: string;
			NO_PLATFORMS: string;
			NO_RELEASE_DATE: string;
			NO_RATING: string;
			NO_SUMMARY: string;
			NO_AGE_RATINGS: string;
			NO_GENRES: string;
		};
		COMMAND_ITUNES_DESCRIPTION: string;
		COMMAND_ITUNES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ITUNES_TITLES: {
			ARTIST: string;
			COLLECTION: string;
			COLLECTION_PRICE: string;
			TRACK_PRICE: string;
			TRACK_RELEASE_DATE: string;
			NUMBER_OF_TRACKS_IN_COLLECTION: string;
			PRIMARY_GENRE: string;
			PREVIEW: string;
			PREVIEW_LABEL: string;
		};
		COMMAND_MOVIES_DESCRIPTION: string;
		COMMAND_MOVIES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MOVIES_TITLES: {
			RUNTIME: string;
			USER_SCORE: string;
			STATUS: string;
			RELEASE_DATE: string;
			IMDB_PAGE: string;
			HOME_PAGE: string;
			COLLECTION: string;
			GENRES: string;
		};
		COMMAND_MOVIES_DATA: {
			VARIABLE_RUNTIME: string;
			MOVIE_IN_PRODUCTION: string;
			LINK_CLICK_HERE: string;
			NONE: string;
			NOT_PART_OF_COLLECTION: string;
			NO_GENRES: string;
		};
		COMMAND_SHOWS_DESCRIPTION: string;
		COMMAND_SHOWS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SHOWS_TITLES: {
			EPISODE_RUNTIME: string;
			USER_SCORE: string;
			STATUS: string;
			FIRST_AIR_DATE: string;
			GENRES: string;
		};
		COMMAND_SHOWS_DATA: {
			VARIABLE_RUNTIME: string;
			UNKNOWN_USER_SCORE: string;
			NO_GENRES: string;
		};
		COMMAND_PRICE_DESCRIPTION: string;
		COMMAND_PRICE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_QUOTE_DESCRIPTION: string;
		COMMAND_QUOTE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ROLES_DESCRIPTION: string;
		COMMAND_ROLES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SEARCH_DESCRIPTION: string;
		COMMAND_SEARCH_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_POLL_DESCRIPTION: string;
		COMMAND_POLL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TOPINVITES_DESCRIPTION: string;
		COMMAND_TOPINVITES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TOPINVITES_NO_INVITES: string;
		COMMAND_TOPINVITES_TOP_10_INVITES_FOR: (params: { guild: Guild }) => string;
		COMMAND_TOPINVITES_EMBED_DATA: {
			CHANNEL: string;
			LINK: string;
			CREATED_AT: string;
			CREATED_AT_UNKNOWN: string;
			EXPIRES_IN: string;
			NEVER_EXPIRES: string;
			TEMPORARY: string;
			USES: string;
		};
		COMMAND_URBAN_DESCRIPTION: string;
		COMMAND_URBAN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WHOIS_DESCRIPTION: string;
		COMMAND_WHOIS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_FOLLOWAGE_DESCRIPTION: string;
		COMMAND_FOLLOWAGE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TWITCH_DESCRIPTION: string;
		COMMAND_TWITCH_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TWITCHSUBSCRIPTION_DESCRIPTION: string;
		COMMAND_TWITCHSUBSCRIPTION_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WIKIPEDIA_DESCRIPTION: string;
		COMMAND_WIKIPEDIA_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_YOUTUBE_DESCRIPTION: string;
		COMMAND_YOUTUBE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WBANG_DESCRIPTION: string;
		COMMAND_WBANG_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WBANGHEAD_DESCRIPTION: string;
		COMMAND_WBANGHEAD_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WBITE_DESCRIPTION: string;
		COMMAND_WBITE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WBLUSH_DESCRIPTION: string;
		COMMAND_WBLUSH_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WCRY_DESCRIPTION: string;
		COMMAND_WCRY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WCUDDLE_DESCRIPTION: string;
		COMMAND_WCUDDLE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WDANCE_DESCRIPTION: string;
		COMMAND_WDANCE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WGREET_DESCRIPTION: string;
		COMMAND_WGREET_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WHUG_DESCRIPTION: string;
		COMMAND_WHUG_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WKISS_DESCRIPTION: string;
		COMMAND_WKISS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WLEWD_DESCRIPTION: string;
		COMMAND_WLEWD_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WLICK_DESCRIPTION: string;
		COMMAND_WLICK_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WNOM_DESCRIPTION: string;
		COMMAND_WNOM_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WNEKO_DESCRIPTION: string;
		COMMAND_WNEKO_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WPAT_DESCRIPTION: string;
		COMMAND_WPAT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WPOUT_DESCRIPTION: string;
		COMMAND_WPOUT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WPUNCH_DESCRIPTION: string;
		COMMAND_WPUNCH_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WSLAP_DESCRIPTION: string;
		COMMAND_WSLAP_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WSLEEPY_DESCRIPTION: string;
		COMMAND_WSLEEPY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WSMILE_DESCRIPTION: string;
		COMMAND_WSMILE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WSMUG_DESCRIPTION: string;
		COMMAND_WSMUG_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WSTARE_DESCRIPTION: string;
		COMMAND_WSTARE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WTHUMBSUP_DESCRIPTION: string;
		COMMAND_WTHUMBSUP_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WTICKLE_DESCRIPTION: string;
		COMMAND_WTICKLE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_ANIME_TYPES: {
			TV: string;
			MOVIE: string;
			OVA: string;
			SPECIAL: string;
			[index: string]: string;
		};
		COMMAND_ANIME_INVALID_CHOICE: string;
		COMMAND_ANIME_OUTPUT_DESCRIPTION: (params: { entry: Kitsu.KitsuHit; synopsis: string | null }) => string;
		COMMAND_ANIME_EMBED_DATA: {
			TYPE: string;
			SCORE: string;
			EPISODES: string;
			EPISODE_LENGTH: string;
			AGE_RATING: string;
			FIRST_AIR_DATE: string;
			WATCH_IT: string;
			STILL_AIRING: string;
		};
		COMMAND_MANGA_OUTPUT_DESCRIPTION: (params: { entry: Kitsu.KitsuHit; synopsis: string | null }) => string;
		COMMAND_MANGA_EMBED_DATA: {
			TYPE: string;
			SCORE: string;
			AGE_RATING: string;
			FIRST_PUBLISH_DATE: string;
			READ_IT: string;
			NONE: string;
		};
		COMMAND_MANGA_TYPES: {
			MANGA: string;
			NOVEL: string;
			MANHWA: string;
			'ONE-SHOT': string;
			SPECIAL: string;
			[index: string]: string;
		};
		COMMAND_WAIFU_FOOTER: string;
		COMMAND_SUBSCRIBE_NO_ROLE: string;
		COMMAND_SUBSCRIBE_SUCCESS: (params: { role: string }) => string;
		COMMAND_UNSUBSCRIBE_SUCCESS: (params: { role: string }) => string;
		COMMAND_SUBSCRIBE_NO_CHANNEL: string;
		COMMAND_ANNOUNCEMENT: (params: { role: string }) => string;
		COMMAND_ANNOUNCEMENT_SUCCESS: string;
		COMMAND_ANNOUNCEMENT_CANCELLED: string;
		COMMAND_ANNOUNCEMENT_PROMPT: string;
		COMMAND_ANNOUNCEMENT_EMBED_MENTIONS: (params: { header: string; mentions: readonly string[] }) => string;
		COMMAND_INVITE_DESCRIPTION: string;
		COMMAND_INVITE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_INVITE: () => string;
		COMMAND_INVITE_NO_PERMS: () => string;
		COMMAND_INFO: string;
		COMMAND_HELP_DATA: {
			TITLE: (params: { description: string }) => string;
			USAGE: (params: { usage: string }) => string;
			EXTENDED: (params: { extendedHelp: string }) => string;
			FOOTER: (params: { name: string }) => string;
		};
		COMMAND_SUPPORT_DESCRIPTION: string;
		COMMAND_SUPPORT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_YARN_DESCRIPTION: string;
		COMMAND_YARN_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_YARN_NO_PACKAGE: string;
		COMMAND_YARN_UNPUBLISHED_PACKAGE: (params: { pkg: string }) => string;
		COMMAND_YARN_PACKAGE_NOT_FOUND: (params: { pkg: string }) => string;
		COMMAND_YARN_EMBED_DATA: {
			DESCRIPTION: (params: {
				author?: string;
				dateCreated: string;
				dateModified: string;
				dependencies: string[] | null;
				deprecated?: string;
				description: string;
				latestVersionNumber: string;
				license: string;
				mainFile: string;
				maintainers: string[];
			}) => string;
			MORE_TEXT: string;
		};
		COMMAND_8BALL_DESCRIPTION: string;
		COMMAND_8BALL_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_8BALL_OUTPUT: (params: { author: string; question: string; response: string }) => string;
		COMMAND_8BALL_QUESTIONS: Record<string, string | RegExp>;
		COMMAND_8BALL_WHEN: () => string;
		COMMAND_8BALL_WHAT: () => string;
		COMMAND_8BALL_HOW_MUCH: () => string;
		COMMAND_8BALL_HOW_MANY: () => string;
		COMMAND_8BALL_WHY: () => string;
		COMMAND_8BALL_WHO: () => string;
		COMMAND_8BALL_ELSE: () => string;
		COMMAND_CATFACT_TITLE: string;
		COMMAND_CHOICE_OUTPUT: (params: { user: string; word: string }) => string;
		COMMAND_CHOICE_MISSING: string;
		COMMAND_CHOICE_DUPLICATES: (params: { words: string }) => string;
		COMMAND_DICE_OUTPUT: (params: { result: number }) => string;
		COMMAND_DICE_ROLLS_ERROR: string;
		COMMAND_DICE_SIDES_ERROR: string;
		COMMAND_ESCAPEROPE_OUTPUT: (params: { user: User }) => string;
		COMMAND_LOVE_LESS45: string;
		COMMAND_LOVE_LESS75: string;
		COMMAND_LOVE_LESS100: string;
		COMMAND_LOVE_100: string;
		COMMAND_LOVE_ITSELF: string;
		COMMAND_LOVE_RESULT: string;
		COMMAND_NORRIS_OUTPUT: string;
		COMMAND_PUN_ERROR: string;
		COMMAND_RATE_OUTPUT: (params: { user: string; rate: number; emoji: string }) => string;
		COMMAND_RATE_MYSELF: [string, string];
		COMMAND_XKCD_COMICS: (params: { amount: number }) => string;
		COMMAND_XKCD_NOTFOUND: string;
		COMMAND_GAMES_SKYRA: string;
		COMMAND_GAMES_BOT: string;
		COMMAND_GAMES_SELF: string;
		COMMAND_GAMES_PROGRESS: string;
		COMMAND_GAMES_NO_PLAYERS: (params: { prefix: string }) => string;
		COMMAND_GAMES_TOO_MANY_OR_FEW: (params: { min: number; max: number }) => string;
		COMMAND_GAMES_REPEAT: string;
		COMMAND_GAMES_PROMPT_TIMEOUT: string;
		COMMAND_GAMES_PROMPT_DENY: string;
		COMMAND_GAMES_TIMEOUT: string;
		COMMAND_C4_DESCRIPTION: string;
		COMMAND_C4_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_C4_PROMPT: (params: { challenger: string; challengee: string }) => string;
		COMMAND_C4_START: (params: { player: string }) => string;
		COMMAND_C4_GAME_COLUMN_FULL: string;
		COMMAND_C4_GAME_WIN: (params: { user: string; turn: number }) => string;
		COMMAND_C4_GAME_DRAW: string;
		COMMAND_C4_GAME_NEXT: (params: { user: string; turn: number }) => string;
		COMMAND_COINFLIP_DESCRIPTION: string;
		COMMAND_COINFLIP_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_COINFLIP_INVALID_COINNAME: (params: { arg: string }) => string;
		COMMAND_COINFLIP_COINNAMES: string[];
		COMMAND_COINFLIP_WIN_TITLE: string;
		COMMAND_COINFLIP_LOSE_TITLE: string;
		COMMAND_COINFLIP_NOGUESS_TITLE: string;
		COMMAND_COINFLIP_WIN_DESCRIPTION: (params: { result: string; wager?: number }) => string;
		COMMAND_COINFLIP_LOSE_DESCRIPTION: (params: { result: string; wager?: number }) => string;
		COMMAND_COINFLIP_NOGUESS_DESCRIPTION: (params: { result: string }) => string;
		COMMAND_HIGHERLOWER_DESCRIPTION: string;
		COMMAND_HIGHERLOWER_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_HIGHERLOWER_LOADING: string;
		COMMAND_HIGHERLOWER_NEWROUND: string;
		COMMAND_HIGHERLOWER_EMBED: {
			TITLE: (params: { turn: number }) => string;
			DESCRIPTION: (params: { number: number }) => string;
			FOOTER: string;
		};
		COMMAND_HIGHERLOWER_LOSE: {
			TITLE: string;
			DESCRIPTION: (params: { number: number; losses: number }) => string;
			FOOTER: string;
		};
		COMMAND_HIGHERLOWER_WIN: {
			TITLE: string;
			DESCRIPTION: (params: { potentials: number; number: number }) => string;
			FOOTER: string;
		};
		COMMAND_HIGHERLOWER_CANCEL: {
			TITLE: string;
			DESCRIPTION: (params: { username: string }) => string;
		};
		COMMAND_HIGHERLOWER_CASHOUT: (params: { amount: number }) => string;
		COMMAND_HUNGERGAMES_DESCRIPTION: string;
		COMMAND_HUNGERGAMES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_HUNGERGAMES_RESULT_HEADER: (params: { game: HungerGamesGame }) => string;
		COMMAND_HUNGERGAMES_RESULT_DEATHS: (params: { deaths: number }) => string;
		COMMAND_HUNGERGAMES_RESULT_PROCEED: string;
		COMMAND_HUNGERGAMES_STOP: string;
		COMMAND_HUNGERGAMES_WINNER: (params: { winner: string }) => string;
		COMMAND_SLOTMACHINE_DESCRIPTION: string;
		COMMAND_SLOTMACHINE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SLOTMACHINES_WIN: (params: { roll: string; winnings: number }) => string;
		COMMAND_SLOTMACHINES_LOSS: (params: { roll: string }) => string;
		COMMAND_SLOTMACHINE_TITLES: {
			PREVIOUS: string;
			NEW: string;
		};
		COMMAND_SLOTMACHINE_CANVAS_TEXT: (params: { won: boolean }) => string;
		COMMAND_TICTACTOE_DESCRIPTION: string;
		COMMAND_TICTACTOE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WHEELOFFORTUNE_DESCRIPTION: string;
		COMMAND_WHEELOFFORTUNE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WHEELOFFORTUNE_CANVAS_TEXT: (params: { won: boolean }) => string;
		COMMAND_WHEELOFFORTUNE_TITLES: {
			PREVIOUS: string;
			NEW: string;
		};
		COMMAND_TICTACTOE_PROMPT: (params: { challenger: string; challengee: string }) => string;
		COMMAND_TICTACTOE_TURN: (params: { icon: string; player: string; board: string }) => string;
		COMMAND_TICTACTOE_WINNER: (params: { winner: string; board: string }) => string;
		COMMAND_TICTACTOE_DRAW: (params: { board: string }) => string;
		COMMAND_TRIVIA_DESCRIPTION: string;
		COMMAND_TRIVIA_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TRIVIA_INVALID_CATEGORY: string;
		COMMAND_TRIVIA_ACTIVE_GAME: string;
		COMMAND_TRIVIA_INCORRECT: (params: { attempt: string }) => string;
		COMMAND_TRIVIA_NO_ANSWER: (params: { correctAnswer: string }) => string;
		COMMAND_TRIVIA_EMBED_TITLES: {
			TRIVIA: string;
			DIFFICULTY: string;
		};
		COMMAND_TRIVIA_WINNER: (params: { winner: string; correctAnswer: string }) => string;
		COMMAND_VAULT_DESCRIPTION: string;
		COMMAND_VAULT_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_VAULT_EMBED_DATA: {
			DEPOSITED_DESCRIPTION: (params: { coins: number }) => string;
			WITHDREW_DESCRIPTION: (params: { coins: number }) => string;
			SHOW_DESCRIPTION: string;
			ACCOUNT_MONEY: string;
			ACCOUNT_VAULT: string;
		};
		COMMAND_VAULT_INVALID_COINS: string;
		COMMAND_VAULT_NOT_ENOUGH_MONEY: (params: { money: number }) => string;
		COMMAND_VAULT_NOT_ENOUGH_IN_VAULT: (params: { vault: number }) => string;
		GIVEAWAY_TIME: string;
		GIVEAWAY_TIME_TOO_LONG: string;
		GIVEAWAY_ENDS_AT: string;
		GIVEAWAY_DURATION: (params: { time: number }) => string;
		GIVEAWAY_TITLE: string;
		GIVEAWAY_LASTCHANCE: (params: { time: number }) => string;
		GIVEAWAY_LASTCHANCE_TITLE: string;
		GIVEAWAY_ENDED: (params: { winners: readonly string[] }) => string;
		GIVEAWAY_ENDED_NO_WINNER: string;
		GIVEAWAY_ENDED_AT: string;
		GIVEAWAY_ENDED_TITLE: string;
		GIVEAWAY_ENDED_MESSAGE: (params: { winners: readonly string[]; title: string }) => string;
		GIVEAWAY_ENDED_MESSAGE_NO_WINNER: (params: { title: string }) => string;
		GIVEAWAY_SCHEDULED: (params: { scheduledTime: number }) => string;
		COMMAND_NICK_SET: (params: { nickname: string }) => string;
		COMMAND_NICK_CLEARED: string;
		COMMAND_PERMISSIONNODES_HIGHER: string;
		COMMAND_PERMISSIONNODES_INVALID_TYPE: string;
		COMMAND_PERMISSIONNODES_ADD: string;
		COMMAND_PERMISSIONNODES_NODE_NOT_EXISTS: string;
		COMMAND_PERMISSIONNODES_COMMAND_NOT_EXISTS: string;
		COMMAND_PERMISSIONNODES_REMOVE: string;
		COMMAND_PERMISSIONNODES_RESET: string;
		COMMAND_PERMISSIONNODES_SHOW: (params: { name: string; allow: readonly string[]; deny: readonly string[] }) => string;
		COMMAND_TRIGGERS_NOTYPE: string;
		COMMAND_TRIGGERS_NOOUTPUT: string;
		COMMAND_TRIGGERS_INVALIDREACTION: string;
		COMMAND_TRIGGERS_INVALIDALIAS: string;
		COMMAND_TRIGGERS_REMOVE_NOTTAKEN: string;
		COMMAND_TRIGGERS_REMOVE: string;
		COMMAND_TRIGGERS_ADD_TAKEN: string;
		COMMAND_TRIGGERS_ADD: string;
		COMMAND_TRIGGERS_LIST_EMPTY: string;
		COMMAND_SERVERINFO_TITLES: Record<string, string>;
		COMMAND_SERVERINFO_ROLES: (params: { roles: string }) => string;
		COMMAND_SERVERINFO_NOROLES: string;
		COMMAND_SERVERINFO_CHANNELS: (params: { text: number; voice: number; categories: number; afkChannel: string; afkTime: number }) => string;
		COMMAND_SERVERINFO_MEMBERS: (params: { count: string; owner: User }) => string;
		COMMAND_SERVERINFO_OTHER: (params: { size: number; region: string; createdAt: number; verificationLevel: 0 | 1 | 2 | 3 | 4 }) => string;
		COMMAND_ROLEINFO_TITLES: Record<string, string>;
		COMMAND_ROLEINFO: (params: { role: Role }) => string;
		COMMAND_ROLEINFO_ALL: string;
		COMMAND_ROLEINFO_PERMISSIONS: (params: { permissions: readonly PermissionString[] }) => string;
		COMMAND_FILTER_UNDEFINED_WORD: string;
		COMMAND_FILTER_FILTERED: (params: { filtered: boolean }) => string;
		COMMAND_FILTER_ADDED: (params: { word: string }) => string;
		COMMAND_FILTER_REMOVED: (params: { word: string }) => string;
		COMMAND_FILTER_RESET: string;
		COMMAND_FILTER_SHOW_EMPTY: string;
		COMMAND_FILTER_SHOW: (params: { words: string }) => string;
		COMMAND_MANAGEATTACHMENTS_REQUIRED_VALUE: string;
		COMMAND_MANAGEATTACHMENTS_INVALID_ACTION: string;
		COMMAND_MANAGEATTACHMENTS_MAXIMUM: (params: { value: number }) => string;
		COMMAND_MANAGEATTACHMENTS_EXPIRE: (params: { value: number }) => string;
		COMMAND_MANAGEATTACHMENTS_DURATION: (params: { value: number }) => string;
		COMMAND_MANAGEATTACHMENTS_ACTION: string;
		COMMAND_MANAGEATTACHMENTS_LOGS: string;
		COMMAND_MANAGEATTACHMENTS_ENABLED: (params: { value: boolean }) => string;
		COMMAND_MANAGECOMMANDAUTODELETE_TEXTCHANNEL: string;
		COMMAND_MANAGECOMMANDAUTODELETE_REQUIRED_DURATION: string;
		COMMAND_MANAGECOMMANDAUTODELETE_SHOW_EMPTY: string;
		COMMAND_MANAGECOMMANDAUTODELETE_SHOW: (params: { codeblock: string }) => string;
		COMMAND_MANAGECOMMANDAUTODELETE_ADD: (params: { channel: string; time: number }) => string;
		COMMAND_MANAGECOMMANDAUTODELETE_REMOVE: (params: { channel: string }) => string;
		COMMAND_MANAGECOMMANDAUTODELETE_REMOVE_NOTSET: (params: { channel: string }) => string;
		COMMAND_MANAGECOMMANDAUTODELETE_RESET: string;
		COMMAND_MANAGECOMMANDCHANNEL_TEXTCHANNEL: string;
		COMMAND_MANAGECOMMANDCHANNEL_REQUIRED_COMMAND: string;
		COMMAND_MANAGECOMMANDCHANNEL_SHOW: (params: { channel: string; commands: string }) => string;
		COMMAND_MANAGECOMMANDCHANNEL_SHOW_EMPTY: string;
		COMMAND_MANAGECOMMANDCHANNEL_ADD_ALREADYSET: string;
		COMMAND_MANAGECOMMANDCHANNEL_ADD: (params: { channel: string; command: string }) => string;
		COMMAND_MANAGECOMMANDCHANNEL_REMOVE_NOTSET: (params: { channel: string }) => string;
		COMMAND_MANAGECOMMANDCHANNEL_REMOVE: (params: { channel: string; command: string }) => string;
		COMMAND_MANAGECOMMANDCHANNEL_RESET_EMPTY: string;
		COMMAND_MANAGECOMMANDCHANNEL_RESET: (params: { channel: string }) => string;
		COMMAND_MANAGEREACTIONROLES_SHOW_EMPTY: string;
		COMMAND_MANAGEREACTIONROLES_ADD_PROMPT: string;
		COMMAND_MANAGEREACTIONROLES_ADD_CHANNEL: (params: { emoji: string; channel: string }) => string;
		COMMAND_MANAGEREACTIONROLES_ADD_MISSING: string;
		COMMAND_MANAGEREACTIONROLES_ADD: (params: { emoji: string; url: string }) => string;
		COMMAND_MANAGEREACTIONROLES_REMOVE_NOTEXISTS: string;
		COMMAND_MANAGEREACTIONROLES_REMOVE: (params: { emoji: string; url: string }) => string;
		COMMAND_MANAGEREACTIONROLES_RESET_EMPTY: string;
		COMMAND_MANAGEREACTIONROLES_RESET: string;
		COMMAND_SETSTARBOARDEMOJI_SET: (params: { emoji: string }) => string;
		CONFIGURATION_TEXTCHANNEL_REQUIRED: string;
		CONFIGURATION_EQUALS: string;
		COMMAND_SETIGNORECHANNELS_SET: (params: { channel: string }) => string;
		COMMAND_SETIGNORECHANNELS_REMOVED: (params: { channel: string }) => string;
		COMMAND_SETIMAGELOGS_SET: (params: { channel: string }) => string;
		COMMAND_SETMEMBERLOGS_SET: (params: { channel: string }) => string;
		COMMAND_SETMESSAGELOGS_SET: (params: { channel: string }) => string;
		COMMAND_SETMODLOGS_SET: (params: { channel: string }) => string;
		COMMAND_SETPREFIX_SET: (params: { prefix: string }) => string;
		COMMAND_STICKYROLES_REQUIRED_USER: string;
		COMMAND_STICKYROLES_REQUIRED_ROLE: string;
		COMMAND_STICKYROLES_NOTEXISTS: (params: { user: string }) => string;
		COMMAND_STICKYROLES_RESET: (params: { user: string }) => string;
		COMMAND_STICKYROLES_REMOVE: (params: { user: string }) => string;
		COMMAND_STICKYROLES_ADD_EXISTS: (params: { user: string }) => string;
		COMMAND_STICKYROLES_ADD: (params: { user: string }) => string;
		COMMAND_STICKYROLES_SHOW_EMPTY: string;
		COMMAND_STICKYROLES_SHOW_SINGLE: (params: { user: string; roles: readonly string[] }) => string;
		COMMAND_RANDREDDIT_REQUIRED_REDDIT: string;
		COMMAND_RANDREDDIT_INVALID_ARGUMENT: string;
		COMMAND_RANDREDDIT_BANNED: string;
		COMMAND_RANDREDDIT_FAIL: string;
		COMMAND_RANDREDDIT_ALL_NSFW: string;
		COMMAND_RANDREDDIT_ALL_NSFL: string;
		COMMAND_RANDREDDIT_MESSAGE: (params: { title: string; author: string; url: string }) => string;
		COMMAND_RANDREDDIT_ERROR_PRIVATE: string;
		COMMAND_RANDREDDIT_ERROR_QUARANTINED: string;
		COMMAND_RANDREDDIT_ERROR_NOT_FOUND: string;
		COMMAND_RANDREDDIT_ERROR_BANNED: string;
		COMMAND_REDDITUSER_DESCRIPTION: string;
		COMMAND_REDDITUSER_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_REDDITUSER_COMPLEXITY_LEVELS: string[];
		COMMAND_REDDITUSER_INVALID_USER: (params: { user: string }) => string;
		COMMAND_REDDITUSER_QUERY_FAILED: string;
		COMMAND_REDDITUSER_TITLES: {
			LINK_KARMA: string;
			COMMENT_KARMA: string;
			TOTAL_COMMENTS: string;
			TOTAL_SUBMISSIONS: string;
			COMMENT_CONTROVERSIALITY: string;
			TEXT_COMPLEXITY: string;
			TOP_5_SUBREDDITS: string;
			BY_SUBMISSIONS: string;
			BY_COMMENTS: string;
			BEST_COMMENT: string;
			WORST_COMMENT: string;
		};
		COMMAND_REDDITUSER_DATA: {
			OVERVIEW_FOR: (params: { user: string }) => string;
			PERMALINK: string;
			DATA_AVAILABLE_FOR: string;
			JOINED_REDDIT: (params: { timestamp: string }) => string;
		};
		COMMAND_SHIP_DESCRIPTION: string;
		COMMAND_SHIP_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_SHIP_DATA: {
			TITLE: (params: { romeoUsername: string; julietUsername: string }) => string;
			DESCRIPTION: (params: { shipName: string }) => string;
		};
		COMMAND_SNIPE_EMPTY: string;
		COMMAND_SNIPE_TITLE: string;
		COMMAND_UPVOTE_MESSAGE: string;
		COMMAND_VAPORWAVE_DESCRIPTION: string;
		COMMAND_VAPORWAVE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_VAPORWAVE_OUTPUT: (params: { str: string }) => string;

		COMMAND_HISTORY_DESCRIPTION: string;
		COMMAND_HISTORY_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_HISTORY_FOOTER: (params: { warnings: number; mutes: number; kicks: number; bans: number }) => string;
		COMMAND_MODERATIONS_DESCRIPTION: string;
		COMMAND_MODERATIONS_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_MODERATIONS_EMPTY: string;
		COMMAND_MODERATIONS_AMOUNT: (params: { amount: number }) => string;
		COMMAND_MUTES_DESCRIPTION: string;
		COMMAND_MUTES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_WARNINGS_DESCRIPTION: string;
		COMMAND_WARNINGS_EXTENDED: LanguageHelpDisplayOptions;

		COMMAND_PERMISSIONS: (params: { username: string; id: string }) => string;
		COMMAND_PERMISSIONS_ALL: string;
		COMMAND_RAID_DISABLED: string;
		COMMAND_RAID_MISSING_KICK: string;
		COMMAND_RAID_LIST: string;
		COMMAND_RAID_CLEAR: string;
		COMMAND_RAID_COOL: string;
		COMMAND_FLOW: (params: { amount: number }) => string;
		COMMAND_TIME_TIMED: string;
		COMMAND_TIME_UNDEFINED_TIME: string;
		COMMAND_TIME_UNSUPPORTED_TIPE: string;
		COMMAND_TIME_NOT_SCHEDULED: string;
		COMMAND_TIME_ABORTED: (params: { title: string }) => string;
		COMMAND_TIME_SCHEDULED: (params: { title: string; user: User; time: number }) => string;
		COMMAND_SLOWMODE_SET: (params: { cooldown: number }) => string;
		COMMAND_SLOWMODE_TOO_LONG: string;
		COMMAND_BAN_NOT_BANNABLE: string;
		COMMAND_DEHOIST_EMBED: {
			TITLE: (params: { users: number }) => string;
			DESCRIPTION_NOONE: string;
			DESCRIPTION_WITHERRORS: (params: { users: number; errored: number }) => string;
			DESCRIPTION: (params: { users: number }) => string;
			FIELD_ERROR_TITLE: string;
		};
		COMMAND_KICK_NOT_KICKABLE: string;
		COMMAND_LOCKDOWN_LOCK: (params: { channel: string }) => string;
		COMMAND_LOCKDOWN_LOCKING: (params: { channel: string }) => string;
		COMMAND_LOCKDOWN_LOCKED: (params: { channel: string }) => string;
		COMMAND_LOCKDOWN_UNLOCKED: (params: { channel: string }) => string;
		COMMAND_LOCKDOWN_OPEN: (params: { channel: string }) => string;
		COMMAND_MUTE_LOWLEVEL: string;
		COMMAND_MUTE_CONFIGURE_CANCELLED: string;
		COMMAND_MUTE_CONFIGURE: string;
		COMMAND_MUTE_CONFIGURE_TOOMANY_ROLES: string;
		COMMAND_MUTE_MUTED: string;
		COMMAND_MUTE_USER_NOT_MUTED: string;
		COMMAND_MUTE_UNCONFIGURED: string;
		COMMAND_MUTECREATE_MISSING_PERMISSION: string;
		COMMAND_RESTRICT_LOWLEVEL: string;
		COMMAND_PRUNE_INVALID: string;
		COMMAND_PRUNE: (params: { amount: number; total: number }) => string;
		COMMAND_PRUNE_INVALID_POSITION: string;
		COMMAND_PRUNE_INVALID_FILTER: string;
		COMMAND_PRUNE_NO_DELETES: string;
		COMMAND_PRUNE_LOG_HEADER: string;
		COMMAND_PRUNE_LOG_MESSAGE: (params: { channel: string; author: string; amount: number }) => string;
		COMMAND_PRUNE_POSITIONS: Map<string, Position>;
		COMMAND_PRUNE_FILTERS: Map<string, Filter>;
		COMMAND_REASON_MISSING_CASE: string;
		COMMAND_REASON_NOT_EXISTS: (params: { range?: boolean }) => string;
		COMMAND_REASON_UPDATED: (params: { entries: readonly number[]; newReason: string }) => string;
		COMMAND_TOGGLEMODERATIONDM_TOGGLED: (params: { value: boolean }) => string;
		COMMAND_UNBAN_MISSING_PERMISSION: string;
		COMMAND_UNMUTE_MISSING_PERMISSION: string;
		COMMAND_VMUTE_MISSING_PERMISSION: string;
		COMMAND_VMUTE_USER_NOT_MUTED: string;
		COMMAND_WARN_DM: (params: { moderator: string; guild: string; reason: string }) => string;
		COMMAND_WARN_MESSAGE: (params: { user: User; log: number }) => string;
		COMMAND_MODERATION_OUTPUT: (params: {
			cases: readonly number[];
			range: string | number;
			users: readonly string[];
			reason: string | null;
		}) => string;
		COMMAND_MODERATION_FAILED: (params: { users: readonly string[] }) => string;
		COMMAND_MODERATION_DM: (params: {
			guild: string;
			title: string;
			reason: string | null;
			duration: number | null;
		}) => {
			DESCRIPTION: string;
			FOOTER: string;
		};
		COMMAND_MODERATION_DAYS: RegExp;
		COMMAND_AUTOROLE_POINTS_REQUIRED: string;
		COMMAND_AUTOROLE_UPDATE_CONFIGURED: string;
		COMMAND_AUTOROLE_UPDATE_UNCONFIGURED: string;
		COMMAND_AUTOROLE_UPDATE: (params: { role: Role; points: number; before: number }) => string;
		COMMAND_AUTOROLE_REMOVE: (params: { role: Role; before: number }) => string;
		COMMAND_AUTOROLE_ADD: (params: { role: Role; points: number }) => string;
		COMMAND_AUTOROLE_LIST_EMPTY: string;
		COMMAND_AUTOROLE_UNKNOWN_ROLE: (params: { role: string }) => string;
		COMMAND_BALANCE: (params: { user: string; amount: number }) => string;
		COMMAND_BALANCE_SELF: (params: { amount: number }) => string;
		COMMAND_BALANCE_BOTS: string;
		COMMAND_SOCIAL_MEMBER_NOTEXISTS: string;
		COMMAND_SOCIAL_ADD: (params: { user: string; amount: number; added: number }) => string;
		COMMAND_SOCIAL_REMOVE: (params: { user: string; amount: number; removed: number }) => string;
		COMMAND_SOCIAL_UNCHANGED: (params: { user: string }) => string;
		COMMAND_SOCIAL_RESET: (params: { user: string }) => string;
		COMMAND_BANNER_MISSING: (params: { type: string }) => string;
		COMMAND_BANNER_NOTEXISTS: (params: { prefix: string }) => string;
		COMMAND_BANNER_USERLIST_EMPTY: (params: { prefix: string }) => string;
		COMMAND_BANNER_RESET_DEFAULT: string;
		COMMAND_BANNER_RESET: string;
		COMMAND_BANNER_SET_NOT_BOUGHT: string;
		COMMAND_BANNER_SET: (params: { banner: string }) => string;
		COMMAND_BANNER_BOUGHT: (params: { prefix: string; banner: string }) => string;
		COMMAND_BANNER_MONEY: (params: { money: number; cost: number }) => string;
		COMMAND_BANNER_PAYMENT_CANCELLED: string;
		COMMAND_BANNER_BUY: (params: { banner: string }) => string;
		COMMAND_BANNER_PROMPT: string;
		COMMAND_TOGGLEDARKMODE_TOGGLED: (params: { enabled: boolean }) => string;
		COMMAND_DAILY_TIME: (params: { time: number }) => string;
		COMMAND_DAILY_TIME_SUCCESS: (params: { amount: number }) => string;
		COMMAND_DAILY_GRACE: (params: { remaining: number }) => string;
		COMMAND_DAILY_GRACE_ACCEPTED: (params: { amount: number; remaining: number }) => string;
		COMMAND_DAILY_GRACE_DENIED: string;
		COMMAND_LEVEL: LevelTitles;
		COMMAND_DIVORCE_NOTTAKEN: string;
		COMMAND_DIVORCE_PROMPT: string;
		COMMAND_DIVORCE_CANCEL: string;
		COMMAND_DIVORCE_DM: (params: { user: string }) => string;
		COMMAND_DIVORCE_SUCCESS: (params: { user: string }) => string;
		COMMAND_MARRY_WITH: (params: { users: readonly string[] }) => string;
		COMMAND_MARRY_NOTTAKEN: string;
		COMMAND_MARRY_SKYRA: string;
		COMMAND_MARRY_SNEYRA: string;
		COMMAND_MARRY_BOTS: string;
		COMMAND_MARRY_SELF: string;
		COMMAND_MARRY_AUTHOR_TAKEN: (params: { author: User }) => string;
		COMMAND_MARRY_AUTHOR_MULTIPLE_CANCEL: (params: { user: string }) => string;
		COMMAND_MARRY_TAKEN: (params: { spousesCount: number }) => string;
		COMMAND_MARRY_ALREADY_MARRIED: (params: { user: User }) => string;
		COMMAND_MARRY_AUTHOR_TOO_MANY: (params: { limit: number }) => string;
		COMMAND_MARRY_TARGET_TOO_MANY: (params: { limit: number }) => string;
		COMMAND_MARRY_MULTIPLE_CANCEL: string;
		COMMAND_MARRY_PETITION: (params: { author: User; user: User }) => string;
		COMMAND_MARRY_NOREPLY: string;
		COMMAND_MARRY_DENIED: string;
		COMMAND_MARRY_ACCEPTED: (params: { author: User; user: User }) => string;
		COMMAND_MYLEVEL: (params: { points: number; next: string; user: string }) => string;
		COMMAND_MYLEVEL_SELF: (params: { points: number; next: string }) => string;
		COMMAND_MYLEVEL_NEXT: (params: { remaining: number; next: number }) => string;
		COMMAND_PAY_MISSING_MONEY: (params: { needed: number; has: number }) => string;
		COMMAND_PAY_PROMPT: (params: { user: string; amount: number }) => string;
		COMMAND_PAY_PROMPT_ACCEPT: (params: { user: string; amount: number }) => string;
		COMMAND_PAY_PROMPT_DENY: string;
		COMMAND_PAY_SELF: string;
		COMMAND_SOCIAL_PAY_BOT: string;
		COMMAND_PROFILE: ProfileTitles;
		COMMAND_REMINDME_CREATE: (params: { id: string }) => string;
		COMMAND_REMINDME_CREATE_NO_DURATION: string;
		COMMAND_REMINDME_CREATE_NO_DESCRIPTION: string;
		COMMAND_REMINDME_DELETE_NO_ID: string;
		COMMAND_REMINDME_DELETE: (params: { task: ScheduleEntity }) => string;
		COMMAND_REMINDME_LIST_EMPTY: string;
		COMMAND_REMINDME_SHOW_FOOTER: (params: { id: number }) => string;
		COMMAND_REMINDME_INVALID_ID: string;
		COMMAND_REMINDME_NOTFOUND: string;
		COMMAND_REPUTATION_TIME: (params: { remaining: number }) => string;
		COMMAND_REPUTATION_USABLE: string;
		COMMAND_REPUTATION_USER_NOTFOUND: string;
		COMMAND_REPUTATION_SELF: string;
		COMMAND_REPUTATION_BOTS: string;
		COMMAND_REPUTATION_GIVE: (params: { user: string }) => string;
		COMMAND_REPUTATIONS_BOTS: string;
		COMMAND_REPUTATIONS_SELF: (params: { points: number }) => string;
		COMMAND_REPUTATIONS: (params: { user: string; points: number }) => string;
		COMMAND_REQUIRE_ROLE: string;
		COMMAND_SCOREBOARD_POSITION: (params: { position: number }) => string;
		COMMAND_SETCOLOR: (params: { color: string }) => string;
		COMMAND_SOCIAL_PROFILE_NOTFOUND: string;
		COMMAND_SOCIAL_PROFILE_BOT: string;
		COMMAND_SOCIAL_PROFILE_DELETE: (params: { user: string; points: number }) => string;
		COMMAND_SOCIAL_POINTS: string;
		COMMAND_SOCIAL_UPDATE: (params: { action: string; amount: number; user: string; before: number; now: number }) => string;
		COMMAND_SUGGEST_NOSETUP: (params: { username: string }) => string;
		COMMAND_SUGGEST_NOSETUP_ASK: (params: { username: string }) => string;
		COMMAND_SUGGEST_NOSETUP_ABORT: string;
		COMMAND_SUGGEST_NOPERMISSIONS: (params: { username: string; channel: string }) => string;
		COMMAND_SUGGEST_CHANNEL_PROMPT: string;
		COMMAND_SUGGEST_TITLE: (params: { id: number }) => string;
		COMMAND_SUGGEST_SUCCESS: (params: { channel: string }) => string;
		COMMAND_RESOLVESUGGESTION_INVALID_ID: string;
		COMMAND_RESOLVESUGGESTION_MESSAGE_NOT_FOUND: string;
		COMMAND_RESOLVESUGGESTION_ID_NOT_FOUND: string;
		COMMAND_RESOLVESUGGESTION_DEFAULT_COMMENT: string;
		COMMAND_RESOLVESUGGESTION_AUTHOR_ADMIN: string;
		COMMAND_RESOLVESUGGESTION_AUTHOR_MODERATOR: string;
		COMMAND_RESOLVESUGGESTION_ACTIONS: {
			ACCEPT: (params: { author: string }) => string;
			CONSIDER: (params: { author: string }) => string;
			DENY: (params: { author: string }) => string;
		};
		COMMAND_RESOLVESUGGESTION_ACTIONS_DMS: {
			ACCEPT: (params: { author: string; guild: string }) => string;
			CONSIDER: (params: { author: string; guild: string }) => string;
			DENY: (params: { author: string; guild: string }) => string;
		};
		COMMAND_RESOLVESUGGESTION_DM_FAIL: string;
		COMMAND_RESOLVESUGGESTION_SUCCESS: (params: { id: number; action: 'accept' | 'a' | 'deny' | 'd' | 'consider' | 'c' }) => string;
		COMMAND_STAR_NOSTARS: string;
		COMMAND_STAR_STATS: string;
		COMMAND_STAR_STATS_DESCRIPTION: (params: { messages: number; stars: number }) => string;
		COMMAND_STAR_TOPSTARRED: string;
		COMMAND_STAR_TOPSTARRED_DESCRIPTION: (params: { medal: string; id: string; stars: number }) => string;
		COMMAND_STAR_TOPRECEIVERS: string;
		COMMAND_STAR_TOPRECEIVERS_DESCRIPTION: (params: { medal: string; id: string; stars: number }) => string;
		COMMAND_EVAL_TIMEOUT: (params: { seconds: number }) => string;
		COMMAND_EVAL_ERROR: (params: { time: string; output: string; type: string }) => string;
		COMMAND_STATS_TITLES: {
			STATS: string;
			UPTIME: string;
			SERVER_USAGE: string;
		};
		COMMAND_STATS_FIELDS: (params: {
			stats: StatsGeneral;
			uptime: StatsUptime;
			usage: StatsUsage;
		}) => {
			STATS: string;
			UPTIME: string;
			SERVER_USAGE: string;
		};
		COMMAND_TAG_DESCRIPTION: string;
		COMMAND_TAG_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_TAG_PERMISSIONLEVEL: string;
		COMMAND_TAG_NAME_NOTALLOWED: string;
		COMMAND_TAG_NAME_TOOLONG: string;
		COMMAND_TAG_LIST_EMPTY: string;
		COMMAND_TAG_CONTENT_REQUIRED: string;
		COMMAND_TAG_EXISTS: (params: { tag: string }) => string;
		COMMAND_TAG_ADDED: (params: { name: string; content: string }) => string;
		COMMAND_TAG_REMOVED: (params: { name: string }) => string;
		COMMAND_TAG_NOTEXISTS: (params: { tag: string }) => string;
		COMMAND_TAG_EDITED: (params: { name: string; content: string }) => string;
		COMMAND_TAG_LIST: (params: { tags: readonly string[] }) => string;
		COMMAND_TAG_RESET: string;
		COMMAND_AVATAR_NONE: string;
		COMMAND_COLOR: (params: { hex: string; rgb: string; hsl: string }) => string;
		COMMAND_EMOJI_CUSTOM: (params: { emoji: string; id: string }) => string;
		COMMAND_EMOJI_TWEMOJI: (params: { emoji: string; id: string }) => string;
		COMMAND_EMOJI_INVALID: string;
		COMMAND_EMOJI_TOO_LARGE: (params: { emoji: string }) => string;
		COMMAND_EMOTES_DESCRIPTION: string;
		COMMAND_EMOTES_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_EMOTES_TITLE: string;
		COMMAND_PRICE_CURRENCY: (params: { fromCurrency: string; fromAmount: number; worths: string[] }) => string;
		COMMAND_PRICE_CURRENCY_NOT_FOUND: string;
		COMMAND_QUOTE_MESSAGE: string;
		COMMAND_ROLES_LIST_EMPTY: string;
		COMMAND_ROLES_ABORT: (params: { prefix: string }) => string;
		COMMAND_ROLES_LIST_TITLE: string;
		COMMAND_ROLES_ADDED: (params: { roles: string }) => string;
		COMMAND_ROLES_REMOVED: (params: { roles: string }) => string;
		COMMAND_ROLES_NOT_PUBLIC: (params: { roles: string }) => string;
		COMMAND_ROLES_NOT_MANAGEABLE: (params: { roles: string }) => string;
		COMMAND_ROLES_AUDITLOG: string;
		COMMAND_DUCKDUCKGO_NOTFOUND: string;
		COMMAND_DUCKDUCKGO_LOOKALSO: string;
		COMMAND_URBAN_NOTFOUND: string;
		COMMAND_URBAN_INDEX_NOTFOUND: string;
		SYSTEM_TEXT_TRUNCATED: (params: { definition: string; url: string }) => string;
		COMMAND_WHOIS_MEMBER_TITLES: {
			JOINED: string;
			CREATED_AT: string;
		};
		COMMAND_WHOIS_MEMBER_FIELDS: (params: {
			member: GuildMember;
		}) => {
			JOINED: string;
			CREATED_AT: string;
			FOOTER: string;
		};
		COMMAND_WHOIS_MEMBER_ROLES: (params: { amount: number }) => string;
		COMMAND_WHOIS_MEMBER_PERMISSIONS: string;
		COMMAND_WHOIS_MEMBER_PERMISSIONS_ALL: string;
		COMMAND_WHOIS_USER_TITLES: {
			CREATED_AT: string;
		};
		COMMAND_WHOIS_USER_FIELDS: (params: {
			user: User;
		}) => {
			CREATED_AT: string;
			FOOTER: string;
		};
		COMMAND_FOLLOWAGE: (params: { user: string; channel: string; time: number }) => string;
		COMMAND_FOLLOWAGE_MISSING_ENTRIES: string;
		COMMAND_FOLLOWAGE_NOT_FOLLOWING: string;
		COMMAND_TWITCH_NO_ENTRIES: string;
		COMMAND_TWITCH_TITLES: {
			FOLLOWERS: string;
			VIEWS: string;
			CLICK_TO_VISIT: string;
			PARTNER: string;
		};
		COMMAND_TWITCH_MATURITY: (params: { mature: boolean }) => string;
		COMMAND_TWITCH_PARTNERSHIP: (params: { affiliateStatus: string | false }) => string;
		COMMAND_TWITCH_AFFILIATE_STATUS: {
			AFFILIATED: string;
			PARTNERED: string;
		};
		COMMAND_TWITCH_CREATED_AT: string;
		COMMAND_TWITCHSUBSCRIPTION_REQUIRED_STREAMER: string;
		COMMAND_TWITCHSUBSCRIPTION_STREAMER_NOT_FOUND: string;
		COMMAND_TWITCHSUBSCRIPTION_REQUIRED_CHANNEL: string;
		COMMAND_TWITCHSUBSCRIPTION_REQUIRED_STATUS: string;
		COMMAND_TWITCHSUBSCRIPTION_STATUS_VALUES: [string, string];
		COMMAND_TWITCHSUBSCRIPTION_INVALID_STATUS: string;
		COMMAND_TWITCHSUBSCRIPTION_REQUIRED_CONTENT: string;
		COMMAND_TWITCHSUBSCRIPTION_ADD_DUPLICATED: string;
		COMMAND_TWITCHSUBSCRIPTION_ADD_SUCCESS: (params: { name: string; channel: string; status: NotificationsStreamsTwitchEventStatus }) => string;
		COMMAND_TWITCHSUBSCRIPTION_REMOVE_STREAMER_NOT_SUBSCRIBED: string;
		COMMAND_TWITCHSUBSCRIPTION_REMOVE_ENTRY_NOT_EXISTS: string;
		COMMAND_TWITCHSUBSCRIPTION_REMOVE_SUCCESS: (params: {
			name: string;
			channel: string;
			status: NotificationsStreamsTwitchEventStatus;
		}) => string;
		COMMAND_TWITCHSUBSCRIPTION_RESET_EMPTY: string;
		COMMAND_TWITCHSUBSCRIPTION_RESET_SUCCESS: (params: { entries: number }) => string;
		COMMAND_TWITCHSUBSCRIPTION_RESET_STREAMER_NOT_SUBSCRIBED: string;
		COMMAND_TWITCHSUBSCRIPTION_RESET_CHANNEL_SUCCESS: (params: { name: string; entries: number }) => string;
		COMMAND_TWITCHSUBSCRIPTION_SHOW_STREAMER_NOT_SUBSCRIBED: string;
		COMMAND_TWITCHSUBSCRIPTION_SHOW_STATUS: [string, string];
		COMMAND_TWITCHSUBSCRIPTION_SHOW_EMPTY: string;
		COMMAND_TWITCHSUBSCRIPTION_SHOW_UNKNOWN_USER: string;
		COMMAND_WIKIPEDIA_NOTFOUND: string;
		COMMAND_YOUTUBE_NOTFOUND: string;
		COMMAND_YOUTUBE_INDEX_NOTFOUND: string;
		COMMAND_DEFINE_DESCRIPTION: string;
		COMMAND_DEFINE_EXTENDED: LanguageHelpDisplayOptions;
		COMMAND_DEFINE_NOTFOUND: string;
		COMMAND_DEFINE_PRONOUNCIATION: string;
		COMMAND_DEFINE_UNKNOWN: string;
		COMMAND_WBANG: (params: { user: string }) => string;
		COMMAND_WBANGHEAD: string;
		COMMAND_WBITE: (params: { user: string }) => string;
		COMMAND_WBLUSH: string;
		COMMAND_WCRY: (params: { user: string }) => string;
		COMMAND_WCUDDLE: (params: { user: string }) => string;
		COMMAND_WDANCE: string;
		COMMAND_WGREET: (params: { user: string }) => string;
		COMMAND_WHUG: (params: { user: string }) => string;
		COMMAND_WKISS: (params: { user: string }) => string;
		COMMAND_WLEWD: string;
		COMMAND_WLICK: (params: { user: string }) => string;
		COMMAND_WNOM: string;
		COMMAND_WNEKO: string;
		COMMAND_WPAT: (params: { user: string }) => string;
		COMMAND_WPOUT: string;
		COMMAND_WPUNCH: (params: { user: string }) => string;
		COMMAND_WSLAP: (params: { user: string }) => string;
		COMMAND_WSLEEPY: string;
		COMMAND_WSMILE: string;
		COMMAND_WSMUG: string;
		COMMAND_WSTARE: (params: { user: string }) => string;
		COMMAND_WTHUMBSUP: string;
		COMMAND_WTICKLE: (params: { user: string }) => string;
		CONST_MONITOR_INVITELINK: string;
		CONST_MONITOR_LINK: string;
		CONST_MONITOR_NMS: string;
		CONST_MONITOR_WORDFILTER: string;
		CONST_MONITOR_CAPSFILTER: string;
		CONST_MONITOR_ATTACHMENTFILTER: string;
		CONST_MONITOR_REACTIONFILTER: string;
		MODERATION_MONITOR_ATTACHMENTS: (params: { amount: number; maximum: number }) => string;
		MODERATION_MONITOR_CAPITALS: (params: { amount: number; maximum: number }) => string;
		MODERATION_MONITOR_INVITES: (params: { amount: number; maximum: number }) => string;
		MODERATION_MONITOR_LINKS: (params: { amount: number; maximum: number }) => string;
		MODERATION_MONITOR_MESSAGES: (params: { amount: number; maximum: number }) => string;
		MODERATION_MONITOR_NEWLINES: (params: { amount: number; maximum: number }) => string;
		MODERATION_MONITOR_WORDS: (params: { amount: number; maximum: number }) => string;
		MONITOR_INVITE_FILTER_ALERT: (params: { user: string }) => string;
		MONITOR_INVITE_FILTER_LOG: (params: { links: readonly string[] }) => string;
		MONITOR_NOLINK: (params: { user: string }) => string;
		MONITOR_WORDFILTER_DM: (params: { filtered: string }) => string;
		MONITOR_CAPSFILTER_DM: (params: { message: string }) => string;
		MONITOR_WORDFILTER: (params: { user: string }) => string;
		MONITOR_CAPSFILTER: (params: { user: string }) => string;
		MONITOR_MESSAGEFILTER: (params: { user: string }) => string;
		MONITOR_NEWLINEFILTER: (params: { user: string }) => string;
		MONITOR_REACTIONSFILTER: (params: { user: string }) => string;
		MONITOR_NMS_MESSAGE: (params: { user: User }) => string;
		MONITOR_NMS_MODLOG: (params: { threshold: number }) => string;
		MONITOR_NMS_ALERT: string;
		MONITOR_SOCIAL_ACHIEVEMENT: string;
		INHIBITOR_SPAM: (params: { channel: string }) => string;
		HG_BLOODBATH: readonly HungerGamesUsage[];
		HG_DAY: readonly HungerGamesUsage[];
		HG_NIGHT: readonly HungerGamesUsage[];
		SERIALIZER_AUTOROLE_INVALID: string;
		SERIALIZER_COMMAND_AUTO_DELETE_INVALID: string;
		SERIALIZER_CUSTOM_COMMAND_INVALID: string;
		SERIALIZER_DISABLED_COMMAND_CHANNEL_INVALID: string;
		SERIALIZER_PERMISSION_NODE_DUPLICATED_COMMAND: (params: { command: string }) => string;
		SERIALIZER_PERMISSION_NODE_INVALID_COMMAND: (params: { command: string }) => string;
		SERIALIZER_PERMISSION_NODE_INVALID_TARGET: string;
		SERIALIZER_PERMISSION_NODE_INVALID: string;
		SERIALIZER_PERMISSION_NODE_SECURITY_EVERYONE_ALLOWS: string;
		SERIALIZER_PERMISSION_NODE_SECURITY_GUARDED: (params: { command: string }) => string;
		SERIALIZER_PERMISSION_NODE_SECURITY_OWNER: string;
		SERIALIZER_REACTION_ROLE_INVALID: string;
		SERIALIZER_STICKY_ROLE_INVALID: string;
		SERIALIZER_TRIGGER_ALIAS_INVALID: string;
		SERIALIZER_TRIGGER_INCLUDE_INVALID: string;
		SERIALIZER_TWITCH_SUBSCRIPTION_INVALID_STREAMER: string;
		SERIALIZER_TWITCH_SUBSCRIPTION_INVALID: string;
		SERIALIZER_UNIQUE_ROLE_SET_INVALID: string;
		SELF_MODERATION_COMMAND_INVALID_MISSING_ACTION: (params: { name: string }) => string;
		SELF_MODERATION_COMMAND_INVALID_MISSING_ARGUMENTS: (params: { name: string }) => string;
		SELF_MODERATION_COMMAND_INVALID_SOFTACTION: (params: { name: string }) => string;
		SELF_MODERATION_COMMAND_INVALID_HARDACTION: (params: { name: string }) => string;
		SELF_MODERATION_COMMAND_ENABLED: string;
		SELF_MODERATION_COMMAND_DISABLED: string;
		SELF_MODERATION_COMMAND_SOFT_ACTION: (params: { value: string }) => string;
		SELF_MODERATION_COMMAND_HARD_ACTION: (params: { value: string }) => string;
		SELF_MODERATION_COMMAND_HARD_ACTION_DURATION: (params: { value: number }) => string;
		SELF_MODERATION_COMMAND_THRESHOLD_MAXIMUM: (params: { value: number }) => string;
		SELF_MODERATION_COMMAND_THRESHOLD_DURATION: (params: { value: number }) => string;
		SELF_MODERATION_COMMAND_SHOW: (params: {
			kEnabled: string;
			kAlert: string;
			kLog: string;
			kDelete: string;
			kHardAction: string;
			hardActionDuration: number;
			thresholdMaximum: number | null;
			thresholdDuration: number | null;
		}) => string;
		SELF_MODERATION_SOFT_ACTION_ALERT: string;
		SELF_MODERATION_SOFT_ACTION_LOG: string;
		SELF_MODERATION_SOFT_ACTION_DELETE: string;
		SELF_MODERATION_HARD_ACTION_BAN: string;
		SELF_MODERATION_HARD_ACTION_KICK: string;
		SELF_MODERATION_HARD_ACTION_MUTE: string;
		SELF_MODERATION_HARD_ACTION_SOFTBAN: string;
		SELF_MODERATION_HARD_ACTION_WARNING: string;
		SELF_MODERATION_HARD_ACTION_NONE: string;
		SELF_MODERATION_ENABLED: string;
		SELF_MODERATION_DISABLED: string;
		SELF_MODERATION_MAXIMUM_TOO_SHORT: (params: { minimum: number; value: number }) => string;
		SELF_MODERATION_MAXIMUM_TOO_LONG: (params: { maximum: number; value: number }) => string;
		SELF_MODERATION_DURATION_TOO_SHORT: (params: { minimum: number; value: number }) => string;
		SELF_MODERATION_DURATION_TOO_LONG: (params: { maximum: number; value: number }) => string;
		ACTION_MUTE_REASON: (params: { reason: string | null }) => string;
		ACTION_UNMUTE_REASON: (params: { reason: string | null }) => string;
		ACTION_KICK_REASON: (params: { reason: string | null }) => string;
		ACTION_SOFTBAN_REASON: (params: { reason: string | null }) => string;
		ACTION_UNSOFTBAN_REASON: (params: { reason: string | null }) => string;
		ACTION_BAN_REASON: (params: { reason: string | null }) => string;
		ACTION_UNBAN_REASON: (params: { reason: string | null }) => string;
		ACTION_VMUTE_REASON: (params: { reason: string | null }) => string;
		ACTION_UNVMUTE_REASON: (params: { reason: string | null }) => string;
		ACTION_VKICK_REASON: (params: { reason: string | null }) => string;
		ACTION_RESTRICTED_REACT_REASON: (params: { reason: string | null }) => string;
		ACTION_RESTRICTED_EMBED_REASON: (params: { reason: string | null }) => string;
		ACTION_RESTRICTED_ATTACHMENT_REASON: (params: { reason: string | null }) => string;
		ACTION_RESTRICTED_VOICE_REASON: (params: { reason: string | null }) => string;
		ACTION_SET_NICKNAME: (params: { reason: string | null; nickname: string }) => string;
		ACTION_ADD_ROLE: (params: { reason: string | null }) => string;
		ACTION_REMOVE_ROLE: (params: { reason: string | null }) => string;
		ACTION_SETUP_MUTE_EXISTS: string;
		ACTION_SETUP_RESTRICTION_EXISTS: string;
		ACTION_SETUP_TOO_MANY_ROLES: string;
		ACTION_SHARED_ROLE_SETUP_EXISTING: string;
		ACTION_SHARED_ROLE_SETUP_EXISTING_NAME: string;
		ACTION_SHARED_ROLE_SETUP_NEW: string;
		ACTION_SHARED_ROLE_SETUP: (params: { role: string; channels: number; permissions: string[] }) => string;
		ACTION_REQUIRED_MEMBER: string;
		MUTE_NOT_CONFIGURED: string;
		RESTRICTION_NOT_CONFIGURED: string;
		MUTE_NOT_IN_MEMBER: string;
		MUTE_LOW_HIERARCHY: string;
		MUTE_CANNOT_MANAGE_ROLES: string;
		MUTE_NOT_EXISTS: string;
		RESOLVER_DATE_SUFFIX: string;
		RESOLVER_POSITIVE_AMOUNT: string;
		POWEREDBY_WEEBSH: string;
		PREFIX_REMINDER: (params: { prefix: string }) => string;
		UNEXPECTED_ISSUE: string;
		COMMAND_DM_NOT_SENT: string;
		COMMAND_DM_SENT: string;
		COMMAND_ROLE_HIGHER_SKYRA: string;
		COMMAND_ROLE_HIGHER: string;
		COMMAND_SUCCESS: string;
		COMMAND_TOSKYRA: string;
		COMMAND_USERSELF: string;
		SYSTEM_FETCHING: () => string;
		SYSTEM_PARSE_ERROR: string;
		SYSTEM_HIGHEST_ROLE: string;
		SYSTEM_CHANNEL_NOT_POSTABLE: string;
		SYSTEM_FETCHBANS_FAIL: string;
		SYSTEM_LOADING: () => string;
		SYSTEM_ERROR: string;
		SYSTEM_DATABASE_ERROR: string;
		SYSTEM_DISCORD_ABORTERROR: string;
		SYSTEM_QUERY_FAIL: string;
		SYSTEM_NO_RESULTS: string;
		SYSTEM_MESSAGE_NOT_FOUND: string;
		SYSTEM_NOTENOUGH_PARAMETERS: string;
		SYSTEM_GUILD_MUTECREATE_APPLYING: (params: { channels: number; role: string }) => string;
		SYSTEM_GUILD_MUTECREATE_EXCEPTIONS: (params: { denied: readonly string[] }) => string;
		SYSTEM_GUILD_MUTECREATE_APPLIED: (params: { accepted: number; exceptions: string; author: string; role: string }) => string;
		SYSTEM_CANNOT_ACCESS_CHANNEL: string;
		SYSTEM_EXCEEDED_LENGTH_OUTPUT: (params: { output: string; time?: string; type?: string }) => string;
		SYSTEM_EXCEEDED_LENGTH_OUTPUT_CONSOLE: (params: { time?: string; type?: string }) => string;
		SYSTEM_EXCEEDED_LENGTH_OUTPUT_FILE: (params: { time?: string; type?: string }) => string;
		SYSTEM_EXCEEDED_LENGTH_OUTPUT_HASTEBIN: (params: { url: string; time?: string; type?: string }) => string;
		SYSTEM_EXCEEDED_LENGTH_CHOOSE_OUTPUT: (params: { output: string[] }) => string;
		SYSTEM_EXTERNAL_SERVER_ERROR: string;
		JUMPTO: string;
		RESOLVER_INVALID_CHANNELNAME: (params: { name: string }) => string;
		RESOLVER_CHANNEL_NOT_IN_GUILD: string;
		RESOLVER_CHANNEL_NOT_IN_GUILD_SUBCOMMAND: (params: { command: string; subcommand: string }) => string;
		RESOLVER_INVALID_ROLENAME: (params: { name: string }) => string;
		RESOLVER_INVALID_USERNAME: (params: { name: string }) => string;
		RESOLVER_MEMBERNAME_USER_LEFT_DURING_PROMPT: string;
		LISTIFY_PAGE: (params: { page: number; pageCount: number; results: string }) => string;
		MODERATION_LOG_APPEALED: string;
		MODERATION_LOG_EXPIRES_IN: (params: { duration: number }) => string;
		MODERATION_LOG_DESCRIPTION: (params: { data: Moderation.ModerationManagerDescriptionData }) => string;
		MODERATION_LOG_FOOTER: (params: { caseID: number }) => string;
		MODERATION_CASE_NOT_EXISTS: string;
		MODERATION_CASES_NOT_EXIST: string;
		GUILD_SETTINGS_CHANNELS_MOD: string;
		GUILD_SETTINGS_ROLES_RESTRICTED: (params: { prefix: string; path: string }) => string;
		GUILD_MUTE_NOT_FOUND: string;
		GUILD_BANS_EMPTY: string;
		GUILD_BANS_NOT_FOUND: string;
		CHANNEL_NOT_READABLE: string;
		USER_NOT_IN_GUILD: string;
		USER_NOT_EXISTENT: string;
		EVENTS_GUILDMEMBERADD: string;
		EVENTS_GUILDMEMBERADD_MUTE: string;
		EVENTS_GUILDMEMBERADD_RAID: string;
		EVENTS_GUILDMEMBERADD_DESCRIPTION: (params: { mention: string; time: number }) => string;
		EVENTS_GUILDMEMBERREMOVE: string;
		EVENTS_GUILDMEMBERKICKED: string;
		EVENTS_GUILDMEMBERBANNED: string;
		EVENTS_GUILDMEMBERSOFTBANNED: string;
		EVENTS_GUILDMEMBERREMOVE_DESCRIPTION: (params: { mention: string; time: number }) => string;
		EVENTS_GUILDMEMBER_UPDATE_NICKNAME: (params: { previous: string; current: string }) => string;
		EVENTS_GUILDMEMBER_ADDED_NICKNAME: (params: { previous: string; current: string }) => string;
		EVENTS_GUILDMEMBER_REMOVED_NICKNAME: (params: { previous: string }) => string;
		EVENTS_GUILDMEMBER_UPDATE_ROLES: (params: { removed: readonly string[]; added: readonly string[] }) => string;
		EVENTS_NICKNAME_UPDATE: string;
		EVENTS_USERNAME_UPDATE: string;
		EVENTS_NAME_DIFFERENCE: (params: { previous: string | null; next: string | null }) => string;
		EVENTS_ROLE_DIFFERENCE: (params: { addedRoles: string[]; removedRoles: string[] }) => string;
		EVENTS_ROLE_UPDATE: string;
		EVENTS_MESSAGE_UPDATE: string;
		EVENTS_MESSAGE_DELETE: string;
		EVENTS_REACTION: string;
		EVENTS_COMMAND: (params: { command: string }) => string;
		SETTINGS_DELETE_CHANNELS_DEFAULT: string;
		SETTINGS_DELETE_ROLES_INITIAL: string;
		SETTINGS_DELETE_ROLES_MUTE: string;
		MODLOG_TIMED: (params: { remaining: number }) => string;
		GUILD_WARN_NOT_FOUND: string;
		GUILD_MEMBER_NOT_VOICECHANNEL: string;
		PROMPTLIST_MULTIPLE_CHOICE: (params: { list: string; amount: number }) => string;
		PROMPTLIST_ATTEMPT_FAILED: (params: { list: string; attempt: number; maxAttempts: number }) => string;
		PROMPTLIST_ABORTED: string;
		FUZZYSEARCH_MATCHES: (params: { matches: number; codeblock: string }) => string;
		FUZZYSEARCH_INVALID_NUMBER: string;
		FUZZYSEARCH_INVALID_INDEX: string;
		EVENTS_ERROR_WTF: string;
		EVENTS_ERROR_STRING: (params: { mention: string; message: string }) => string;
		CONST_USERS: string;
		CONST_MONITOR_MESSAGEFILTER: string;
		CONST_MONITOR_NEWLINEFILTER: string;
		UNKNOWN_CHANNEL: string;
		UNKNOWN_ROLE: string;
		UNKNOWN_USER: string;
		NOTIFICATIONS_TWITCH_NO_GAME_NAME: string;
		NOTIFICATIONS_TWITCH_EMBED_DESCRIPTION: (params: { userName: string; gameName: string | undefined }) => string;
		NOTIFICATION_TWITCH_EMBED_FOOTER: string;
	}
}
